import { get, writable, type Readable } from 'svelte/store';
import type { MakeCodeProject as MkcProject } from '@microbit/makecode-embed';
import {
  createMakeCodeDriver,
  makeCodeIframeUrl,
  makeCodeEditorOrigin,
  createSerialMonitorBridge,
  sendSerialLineToEditor,
  JacdacHost,
  parseExtensions,
  removeExtension,
  getHardwareVersion,
  setHardwareVersion,
  type DriverHandle,
  type MakeCodeExtension,
  type MakeCodeMode,
  type CalliopeHardwareVersion,
  type ShareResult,
} from '@calliope-edu/mini-connection-widget/makecode';
import { calliopeState } from '@calliope-edu/mini-connection-widget';
import {
  generateProject as generateProjectImpl,
  autogeneratedSource,
  createCalliopeSeedProject,
  type GenerateOptions,
} from './makecode/generate';
import { teachableExtensionSource } from './makecode/extension';
import { highestClassIndex, storedMode, usesPoseBlocks } from './makecode/programFiles';
import {
  activeModel,
  addMakeCodeProgram,
  updateMakeCodeProgramFiles,
  getCurrentMakeCodeProgram,
} from './stores/projects';

export const MAKECODE_BASE_URL = 'https://makecode.calliope.cc';
export const CONTROLLER_ID = 'CalliopeTeachable';
/** Owner key in the widget's serial-consumer registry. */
const SERIAL_CONSUMER_ID = 'teachable-makecode';

export type MakeCodeProject = MkcProject;

export { createCalliopeSeedProject };
export type { GenerateOptions, MakeCodeExtension, MakeCodeMode, ShareResult };

/** Origin every message to and from the editor is checked against. */
export const MAKECODE_ORIGIN = makeCodeEditorOrigin(MAKECODE_BASE_URL);

export function createMakeCodeIframeUrl(lang?: string): string {
  return makeCodeIframeUrl({ baseUrl: MAKECODE_BASE_URL, lang });
}

// ---- Driver lifecycle ----
// We maintain a single active driver for the currently-mounted MakeCode iframe.

type DownloadHandler = (d: { name: string; hex: string }) => void;

interface Active {
  iframe: HTMLIFrameElement;
  handle: DriverHandle;
  pending: MakeCodeProject | null;
  downloadHandlers: Set<DownloadHandler>;
  dispose: () => void;
}

let active: Active | null = null;

const projectStore = writable<MakeCodeProject | null>(null);
const readyStore = writable(false);
const modeStore = writable<MakeCodeMode>('blocks');
const extensionsStore = writable<MakeCodeExtension[]>([]);
const hardwareVersionStore = writable<CalliopeHardwareVersion | null>(null);

/** The project as MakeCode last saved it. */
export const makeCodeProject: Readable<MakeCodeProject | null> = {
  subscribe: projectStore.subscribe,
};
export const makeCodeReady: Readable<boolean> = { subscribe: readyStore.subscribe };
export const makeCodeMode: Readable<MakeCodeMode> = { subscribe: modeStore.subscribe };
export const makeCodeExtensions: Readable<MakeCodeExtension[]> = {
  subscribe: extensionsStore.subscribe,
};
export const makeCodeHardwareVersion: Readable<CalliopeHardwareVersion | null> = {
  subscribe: hardwareVersionStore.subscribe,
};

/** Re-read what the toolbar shows about the project. */
function refreshProjectFacts(project: MakeCodeProject | null): void {
  extensionsStore.set(project ? parseExtensions(project) : []);
  hardwareVersionStore.set(project ? getHardwareVersion(project) : null);
}

function disposeActive() {
  if (!active) return;
  active.dispose();
  readyStore.set(false);
  active = null;
}

export function setMakecodeIframe(iframe: HTMLIFrameElement | null) {
  if (!iframe) {
    disposeActive();
    return;
  }
  if (active && active.iframe === iframe) return;
  disposeActive();

  const downloadHandlers = new Set<DownloadHandler>();

  const handle = createMakeCodeDriver({
    iframe,
    controllerId: CONTROLLER_ID,
    // Replaced right after construction with whatever the caller staged; the
    // list is only read when the iframe runs its workspacesync.
    initialProjects: [createCalliopeSeedProject()],
    onEditorReady: () => readyStore.set(true),
    onWorkspaceSave: (project) => {
      projectStore.set(project);
      refreshProjectFacts(project);

      // Persist into the current program so reloads don't lose work.
      const files = (project.text ?? {}) as Record<string, string>;
      if (Object.keys(files).length === 0) return;
      const current = getCurrentMakeCodeProgram();
      if (current) {
        updateMakeCodeProgramFiles(current.id, files, project.header);
      } else {
        // First-ever save with no program slot yet — create one so the user
        // doesn't lose their edits if they reload before clicking anywhere else.
        addMakeCodeProgram({ name: 'Programm 1', files, header: project.header });
      }
    },
    // Teachable fans the compiled hex out to its own handlers — the tryout page
    // flashes it under the project's name — rather than letting the shared
    // driver flash it directly.
    onDownload: (d) => {
      downloadHandlers.forEach((h) => {
        try {
          h(d);
        } catch {
          /* one bad handler must not stop the others */
        }
      });
    },
    // "Als Datei herunterladen" falls through to the widget's downloadHexFile.
  });

  // ---- Serial monitor bridge ----
  // In controller=2 the widget owns the device, so pxt can never open its own
  // serial and its monitor would stay empty. Forwarding the device's lines in
  // is also what raises the "Show data — Device" badge. Declaring the serial
  // consumer gets a flash-only mini 2 the widget's "Serial verbinden?" offer,
  // which Teachable needs anyway to stream its predictions to the board.
  const serialBridge = createSerialMonitorBridge({
    iframe: () => active?.iframe ?? null,
    origin: MAKECODE_ORIGIN,
    consumerId: SERIAL_CONSUMER_ID,
  });

  // ---- Jacdac bridge ----
  // The embed driver handles only the controller protocol and silently drops
  // `messagepacket`, so Jacdac frames need their own raw window listener.
  // Inert until a Jacdac program is on the device.
  const jacdacHost = new JacdacHost({
    iframe: () => active?.iframe ?? null,
    origin: MAKECODE_ORIGIN,
  });
  const onWindowMessage = (event: MessageEvent) => {
    if (event.source !== iframe.contentWindow) return;
    if (event.origin !== MAKECODE_ORIGIN) return;
    // Same gate as the serial bridge: the Blocks LIVE runtime multiplexes
    // binary frames over the serial link, leaving no valid path for Jacdac.
    if (get(calliopeState).programType === 'blocks') return;
    jacdacHost.handleMessage(event.data);
  };
  window.addEventListener('message', onWindowMessage);

  active = {
    iframe,
    handle,
    pending: null,
    downloadHandlers,
    dispose: () => {
      window.removeEventListener('message', onWindowMessage);
      jacdacHost.dispose();
      serialBridge.dispose();
      handle.dispose();
    },
  };
}

/** Push a fully-formed MakeCode project into the editor. */
export function importProject(project: MakeCodeProject): boolean {
  if (!active) return false;
  active.pending = project;
  // Also stage it for the workspacesync: an import issued before the iframe has
  // connected would otherwise be answered with the seed project.
  active.handle.setPendingProjects([project]);
  refreshProjectFacts(project);
  try {
    void active.handle.driver.importProject({ project });
    return true;
  } catch {
    return false;
  }
}

/** Generate a Calliope-targeted project from Teachable app state and import it. */
export function importFromState(opts: GenerateOptions): boolean {
  return importProject(generateProjectImpl(opts));
}

/**
 * Rewrite the generated half of a stored program: `teachable.ts` and
 * `autogenerated.ts`.
 *
 * The file map is persisted verbatim on every autosave, so a program saved
 * before a wire-protocol change would keep parsing the old `teachable.ts`
 * forever, and its class list would keep naming the model it was created from.
 * Neither file is the student's — their work is in `main.blocks` / `main.ts` —
 * so both are rewritten on the way in. That is also what points a program at
 * whichever model is loaded: same class slots, the current model's names.
 *
 * The mode is the union of the model's and the program's own: regenerating for
 * an image model would otherwise drop the pose blocks a program is using.
 */
function withCurrentGenerated(files: Record<string, string>): Record<string, string> {
  const model = get(activeModel);
  const mode =
    model?.mode === 'pose' || storedMode(files) === 'pose' || usesPoseBlocks(files)
      ? 'pose'
      : 'image';
  const next = { ...files };
  if (next['teachable.ts']) next['teachable.ts'] = teachableExtensionSource(mode);
  if (next['autogenerated.ts']) {
    next['autogenerated.ts'] = autogeneratedSource({
      classes: model?.classes ?? [],
      mode,
      // A block the student placed must keep resolving even when the loaded
      // model has fewer classes than the program was built with.
      minClassCount: highestClassIndex(files),
    });
  }
  return next;
}

/**
 * Push a saved MakeCodeProgram's file map into the editor, with its generated
 * files brought up to date against the loaded model. MakeCode's next autosave
 * persists what went in, so the stored program follows along on its own.
 */
export function importProgramFiles(
  files: Record<string, string>,
  header?: unknown,
): boolean {
  return importProject({
    header: header as MkcProject['header'],
    text: withCurrentGenerated(files),
  });
}

/**
 * Push the open program back into the editor. Called after the loaded model
 * changes: the class slots stay where they are, but their names come from that
 * model, so the blocks on screen have to be re-labelled. A no-op when no editor
 * is mounted, which is every view except Programmieren.
 */
export function reimportCurrentProgram(): boolean {
  if (!active) return false;
  const program = getCurrentMakeCodeProgram();
  if (!program) return false;
  return importProgramFiles(program.files, program.header);
}

/** Expose the generator for callers that want to inspect/persist the project. */
export const generateProject = generateProjectImpl;

export async function switchMakeCodeLang(mode: MakeCodeMode): Promise<void> {
  modeStore.set(mode);
  if (!active) return;
  try {
    if (mode === 'blocks') await active.handle.driver.switchBlocks();
    else if (mode === 'javascript') await active.handle.driver.switchJavascript();
    else await active.handle.driver.switchPython();
  } catch {
    /* driver not ready — user can try again */
  }
}

/**
 * Ask MakeCode to compile the current program. The resulting hex arrives
 * asynchronously through `onMakeCodeDownload`, which is where the flash is
 * kicked off — so this resolves once the request is sent, not once the board
 * has the program.
 */
export async function compileMakeCodeProject(): Promise<void> {
  if (!active) return;
  await active.handle.driver.compile();
}

export function onMakeCodeDownload(cb: DownloadHandler): () => void {
  if (!active) return () => {};
  active.downloadHandlers.add(cb);
  return () => active?.downloadHandlers.delete(cb);
}

// ---- Toolbar actions --------------------------------------------------------

/**
 * The project the toolbar acts on: MakeCode's last save when there is one, else
 * the stored program's file map, which is what a freshly-opened editor still
 * holds before its first autosave.
 */
function currentEditableProject(): MakeCodeProject | null {
  const saved = get(projectStore);
  if (saved?.text && Object.keys(saved.text).length > 0) return saved;
  const program = getCurrentMakeCodeProgram();
  if (!program) return null;
  return { header: program.header as MkcProject['header'], text: program.files };
}

/** Persist a toolbar-driven project change and push it back into the editor. */
function applyProjectChange(next: MakeCodeProject): void {
  const files = (next.text ?? {}) as Record<string, string>;
  const program = getCurrentMakeCodeProgram();
  if (program) updateMakeCodeProgramFiles(program.id, files, next.header);
  projectStore.set(next);
  importProject(next);
}

/**
 * Switch the project's Calliope mini revision. pxt-calliope carries the board
 * in the project's `v1`/`v2`/`v3` dependency, so this is a pxt.json rewrite
 * plus a re-import — there is no controller action for it.
 */
export function setMakeCodeHardwareVersion(version: CalliopeHardwareVersion): void {
  const project = currentEditableProject();
  if (!project) return;
  const next = setHardwareVersion(project, version) as MakeCodeProject;
  if (next === project) return;
  applyProjectChange(next);
}

export function removeMakeCodeExtension(extensionId: string): void {
  const project = currentEditableProject();
  if (!project) return;
  const next = removeExtension(project, extensionId) as MakeCodeProject;
  if (next === project) return;
  applyProjectChange(next);
}

/**
 * Publish the active program and return its public URL + QR. The editor runs
 * with `hidemenu=1`, so pxt's own share UI is hidden and this is the only route.
 */
export async function shareMakeCodeProject(projectName: string): Promise<ShareResult> {
  if (!active) throw new Error('editor not ready');
  const headerId =
    (get(projectStore)?.header as { id?: string } | undefined)?.id ??
    (getCurrentMakeCodeProgram()?.header as { id?: string } | undefined)?.id;
  if (!headerId) throw new Error('no program to share');
  // shareProject awaits a postMessage reply; if the share service is
  // unreachable that reply never arrives, so bound the wait.
  const timeout = new Promise<never>((_, reject) =>
    setTimeout(() => reject(new Error('share timeout')), 25000),
  );
  return Promise.race([
    active.handle.driver.shareProject({ headerId, projectName }),
    timeout,
  ]);
}

/**
 * Feed one line to the editor. The serial monitor always shows it; a running
 * simulator receives it as `serial.readLine()` input on a pxt carrying the
 * simdriver forwarding fix. This is how live predictions reach the simulator
 * when no board is connected.
 */
export function sendLineToMakeCode(line: string): boolean {
  if (!active) return false;
  return sendSerialLineToEditor(active.iframe, MAKECODE_ORIGIN, line);
}

// ---- Back-compat shims for existing callers ----

export function generateMakeCodeProject(
  name: string,
  classNames: string[],
  exs: Record<string, { data: string }[]>,
  mode: 'image' | 'pose' = 'image',
): MakeCodeProject {
  return generateProjectImpl({
    name,
    mode,
    classes: classNames,
    dataset: exs,
  });
}

export async function downloadMakeCodeProject(
  name: string,
  classNames: string[],
  exs: Record<string, { data: string }[]>,
  mode: 'image' | 'pose' = 'image',
) {
  const JSZip = (await import('jszip')).default;
  const { saveAs } = await import('file-saver');
  const project = generateMakeCodeProject(name, classNames, exs, mode);
  const zip = new JSZip();
  Object.entries(project.text ?? {}).forEach(([k, v]) => zip.file(k, v));
  const blob = await zip.generateAsync({ type: 'blob' });
  const safe = (project.header?.name ?? name).toString().replace(/\s+/g, '_');
  saveAs(blob, `${safe}_makecode_project_${Date.now()}.zip`);
}

export async function importProjectZip(file: File): Promise<boolean> {
  const JSZip = (await import('jszip')).default;
  const zip = await JSZip.loadAsync(await file.arrayBuffer());
  const text: Record<string, string> = {};
  for (const path of Object.keys(zip.files)) {
    const entry = zip.files[path];
    if (entry.dir) continue;
    try {
      const name = path.split('/').pop() || path;
      text[name] = await entry.async('string');
    } catch {
      // skip binary
    }
  }
  return importProject({ header: undefined, text });
}
