import { examples, classes } from './stores';
import { get } from 'svelte/store';

export type MakeCodeProject = {
  header?: any;
  files?: Record<string, string>;
};

export function generateAutogeneratedTs(classNames: string[] = []) {
  const sanitized = classNames.map((c, idx) => ({ id: idx + 2, varName: sanitizeForVar(c), label: c }));

  const lines = [`namespace ml {`, `  export namespace event {`, `    export const Unknown = new MlEvent(1, "unknown");`];

  for (const s of sanitized) {
    lines.push(`    export const ${s.varName} = new MlEvent(${s.id}, "${s.label}");`);
  }

  lines.push(`  }`, `}`);
  return lines.join('\n');
}

function sanitizeForVar(s: string) {
  return s.replace(/[^a-zA-Z0-9_$]/g, '_').replace(/^[0-9]/, '_$&');
}

export function generateDatasetJson(classNames: string[] = [], exs: Record<string, { data: string }[]> = {}) {
  const data = classNames.map((c, i) => ({ name: c, id: i + 1, recordings: (exs[c] || []).map(x => ({ data: x.data })) }));
  return JSON.stringify({ data }, null, 2);
}

export function generatePxtJson(name = 'Teachable Project') {
  const pxt = {
    name,
    description: '',
    dependencies: {
      core: '*',
      v3: '*',
      'machine-learning': 'github:microbit-foundation/pxt-microbit-ml#v1.0.14'
    },
    files: [ 'main.ts', 'autogenerated.ts', 'dataset.json', 'pxt.json' ],
    preferredEditor: 'blocksprj'
  };
  return JSON.stringify(pxt, null, 2);
}

export function generateMakeCodeProject(name: string, classNames: string[], exs: Record<string, { data: string }[]>) {
  const files: Record<string, string> = {};
  files['pxt.json'] = generatePxtJson(name);
  files['autogenerated.ts'] = generateAutogeneratedTs(classNames);
  files['dataset.json'] = generateDatasetJson(classNames, exs);
  files['main.ts'] = `// generate preview main.ts`;
  return { header: { name }, files } as MakeCodeProject;
}

let iframeRef: HTMLIFrameElement | null = null;
let _pendingProject: MakeCodeProject | null = null;

export function setMakecodeIframe(iframe: HTMLIFrameElement | null) {
  iframeRef = iframe;
  // if we have a pending project queued while iframe was not ready, try import
  if (iframeRef && _pendingProject) {
    try {
      iframeRef.contentWindow?.postMessage({ type: 'pxteditor', id: Math.random().toString(), action: 'importproject', project: _pendingProject, response: true }, '*');
      _pendingProject = null;
    } catch (err) {
      // ignore
    }
  }
}

export function importProject(project: MakeCodeProject) {
  if (!iframeRef || !iframeRef.contentWindow) {
    _pendingProject = project;
    return false;
  }
  const msg = {
    type: 'pxteditor',
    id: Math.random().toString(),
    action: 'importproject',
    project,
    response: true
  };
  iframeRef.contentWindow.postMessage(msg, '*');
  return true;
}

export function sendMessage(action: string, payload?: any) {
  if (!iframeRef || !iframeRef.contentWindow) return false;
  const msg: any = { type: 'pxteditor', id: Math.random().toString(), action, response: true };
  if (payload) Object.assign(msg, payload);
  iframeRef.contentWindow.postMessage(msg, '*');
  return true;
}

export async function downloadMakeCodeProject(name: string, classNames: string[], exs: Record<string, { data: string }[]>) {
  const JSZip = (await import('jszip')).default;
  const saveAsModule = await import('file-saver');
  const { saveAs } = saveAsModule;
  const project = generateMakeCodeProject(name, classNames, exs);
  const zip = new JSZip();
  Object.entries(project.files || {}).forEach(([k, v]) => zip.file(k, v));
  zip.file('pxt.json', project.files?.['pxt.json'] || generatePxtJson(name));
  const content = await zip.generateAsync({ type: 'blob' });
  saveAs(content, `${(project.header?.name || name).replace(/\s+/g, '_')}_makecode_project_${Date.now()}.zip`);
}

export async function importProjectZip(file: File) {
  const JSZip = (await import('jszip')).default;
  const zip = await JSZip.loadAsync(await file.arrayBuffer());
  const files: Record<string, string> = {};
  for (const path of Object.keys(zip.files)) {
    const f = zip.files[path];
    if (f.dir) continue;
    try {
      const text = await f.async('string');
      const name = path.split('/').pop() || path;
      files[name] = text;
    } catch (err) {
      // binary files will be skipped
    }
  }
  return importProject({ header: { name: file.name }, files });
}
