import { writable, derived, get } from 'svelte/store';
import { idbPut, idbGet, idbGetAll, idbDelete, STORES } from '$lib/db';

export type TrainingHistory = {
  epochs: number[];
  accuracy: number[];
  loss: number[];
};

export type ModelMetadata = {
  name: string;
  date: string;
  version: string;
  classes: string[];
  params?: number;
  layers?: number;
  sizeBytes?: number;
};

export type ModelArtifacts = {
  topology: unknown;
  weightSpecs: unknown[];
  weightData: ArrayBuffer;
};

export type FeatureExtractor = 'mobilenet-v1' | 'mobilenet-v2' | 'mobilenet-v1-lite';

// Extractors that used to be offered but were served through tfhub.dev, which now
// redirects to Kaggle and no longer answers browser fetches (CORS/403). Old projects
// may still reference them, so map each onto a supported extractor. 'mobilenet-v2-lite'
// maps to 'mobilenet-v2' because both produce a 1280-dim embedding, which keeps
// already-trained classifier heads loadable.
const LEGACY_FEATURE_EXTRACTORS: Record<string, FeatureExtractor> = {
  'mobilenet-v2-lite': 'mobilenet-v2',
  'mobilenet-v3-small': 'mobilenet-v1',
  'efficientnet-lite0': 'mobilenet-v1'
};

const SUPPORTED_FEATURE_EXTRACTORS: FeatureExtractor[] = [
  'mobilenet-v1',
  'mobilenet-v2',
  'mobilenet-v1-lite'
];

/** Normalise a persisted/unknown extractor id onto one we can actually load. */
export function resolveFeatureExtractor(value: unknown): FeatureExtractor {
  if (typeof value !== 'string') return 'mobilenet-v1';
  if (SUPPORTED_FEATURE_EXTRACTORS.includes(value as FeatureExtractor)) {
    return value as FeatureExtractor;
  }
  return LEGACY_FEATURE_EXTRACTORS[value] ?? 'mobilenet-v1';
}

export type Optimizer = 'adam' | 'sgd' | 'rmsprop';

export type AugmentationSettings = {
  horizontalFlip: boolean;
  rotationDegrees: number;    // +/- deg
  brightnessJitter: number;   // +/- fraction
  zoomJitter: number;         // +/- fraction (random crop size)
  multiplier: number;         // extra copies per original (0..6)
};

export const DEFAULT_AUGMENTATION: AugmentationSettings = {
  horizontalFlip: false,
  rotationDegrees: 10,
  brightnessJitter: 0.15,
  zoomJitter: 0.1,
  multiplier: 2
};

export type TrainingOptions = {
  epochs: number;
  batchSize: number;
  learningRate: number;
  hiddenUnits: number;
  augmentation: boolean;
  augmentationSettings: AugmentationSettings;
  featureExtractor: FeatureExtractor;
  optimizer: Optimizer;
  dropout: number;           // 0..0.9
  validationSplit: number;   // 0..0.5
  earlyStopLoss: number;     // 0 = off
};

export const DEFAULT_TRAINING_OPTIONS: TrainingOptions = {
  epochs: 30,
  batchSize: 16,
  learningRate: 0.001,
  hiddenUnits: 64,
  augmentation: true,
  augmentationSettings: { ...DEFAULT_AUGMENTATION },
  featureExtractor: 'mobilenet-v1',
  optimizer: 'adam',
  dropout: 0.2,
  validationSplit: 0.15,
  earlyStopLoss: 0
};

export type ProjectMode = 'image' | 'pose';

export type Roi = { x: number; y: number; w: number; h: number };

export type TrainedModel = {
  id: string;
  trainedAt: number;
  label?: string;
  artifacts: ModelArtifacts;
  metadata: ModelMetadata;
  history: TrainingHistory;
  options: TrainingOptions;
  classesSnapshot: string[];
  exampleCounts: Record<string, number>;
  roi?: Roi;
  featureExtractor?: FeatureExtractor;
};

/**
 * A saved MakeCode program within a Teachable project. Carries the full
 * MakeCode file map (`text`) so we can push it back into the editor on reload
 * or when the user switches between programs in the sidebar.
 */
export type MakeCodeProgram = {
  id: string;
  name: string;
  createdAt: number;
  updatedAt: number;
  /** The MakeCodeProject file map, e.g. { 'main.ts': '...', 'main.blocks': '...', ... } */
  files: Record<string, string>;
  /** Optional MakeCodeProject header carried over from workspace save. */
  header?: unknown;
  /**
   * Snapshot of the `{ classes, thresholds, mode }` signature that was current
   * when this program was created. Compared against the project's current state
   * to surface an "outdated" hint in the UI — legacy programs are preserved
   * as-is (we never silently regenerate their `teachable.ts` / `autogenerated.ts`).
   */
  classesSnapshot?: string[];
  thresholdsSnapshot?: Record<string, number>;
  modeSnapshot?: ProjectMode;
};

export type Project = {
  id: string;
  name: string;
  mode: ProjectMode;
  createdAt: number;
  updatedAt: number;
  classes: string[];
  examples: Record<string, { data: string }[]>;
  activeClass: string | null;
  trainingOptions: TrainingOptions;
  trainingHistory: TrainingHistory;
  modelMetadata: ModelMetadata;
  modelArtifacts: ModelArtifacts | null;
  modelHistory: TrainedModel[];
  currentModelId: string | null;
  classThresholds?: Record<string, number>;
  makeCodePrograms?: MakeCodeProgram[];
  currentProgramId?: string | null;
};

export type ProjectSummary = {
  id: string;
  name: string;
  mode: ProjectMode;
  createdAt: number;
  updatedAt: number;
  classCount: number;
  hasModel: boolean;
};

const LAST_PROJECT_KEY = 'teachable-last-project-id';

function genId(): string {
  return `prj_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
}

function defaultName(): string {
  const now = new Date();
  const d = now.toLocaleDateString('de-DE', { day: '2-digit', month: '2-digit', year: 'numeric' });
  return `Neues Projekt ${d}`;
}

export function createBlankProject(name?: string, mode: ProjectMode = 'image'): Project {
  const now = Date.now();
  return {
    id: genId(),
    name: name || defaultName(),
    mode,
    createdAt: now,
    updatedAt: now,
    classes: [],
    examples: {},
    activeClass: null,
    trainingOptions: { ...DEFAULT_TRAINING_OPTIONS },
    trainingHistory: { epochs: [], accuracy: [], loss: [] },
    modelMetadata: { name: 'Teachable Machine Model', date: new Date().toISOString(), version: '1.0', classes: [] },
    modelArtifacts: null,
    modelHistory: [],
    currentModelId: null,
    classThresholds: {}
  };
}

// Backfill fields introduced after earlier projects were saved
function hydrate(p: Project): Project {
  if (!p.modelHistory) p.modelHistory = [];
  if (p.currentModelId === undefined) p.currentModelId = null;
  if (!p.classThresholds) p.classThresholds = {};
  if (!p.makeCodePrograms) p.makeCodePrograms = [];
  if (p.currentProgramId === undefined) p.currentProgramId = null;
  if (p.trainingOptions) {
    p.trainingOptions.featureExtractor = resolveFeatureExtractor(p.trainingOptions.featureExtractor);
  }
  return p;
}

function genProgramId(): string {
  return `pgm_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 6)}`;
}

/** Add a new MakeCode program to the current project and make it active. */
export function addMakeCodeProgram(init: {
  name?: string;
  files: Record<string, string>;
  header?: unknown;
}): MakeCodeProgram | null {
  const p = get(currentProject);
  if (!p) return null;
  const now = Date.now();
  const program: MakeCodeProgram = {
    id: genProgramId(),
    name: init.name || `Programm ${(p.makeCodePrograms?.length ?? 0) + 1}`,
    createdAt: now,
    updatedAt: now,
    files: init.files,
    header: init.header,
    classesSnapshot: [...(p.classes ?? [])],
    thresholdsSnapshot: { ...(p.classThresholds ?? {}) },
    modeSnapshot: p.mode,
  };
  updateProject((proj) => {
    if (!proj.makeCodePrograms) proj.makeCodePrograms = [];
    proj.makeCodePrograms.push(program);
    proj.currentProgramId = program.id;
  });
  return program;
}

export function selectMakeCodeProgram(id: string): MakeCodeProgram | null {
  const p = get(currentProject);
  if (!p) return null;
  const found = (p.makeCodePrograms ?? []).find((x) => x.id === id);
  if (!found) return null;
  updateProject((proj) => {
    proj.currentProgramId = id;
  });
  return found;
}

export function renameMakeCodeProgram(id: string, name: string): void {
  updateProject((proj) => {
    if (!proj.makeCodePrograms) return;
    proj.makeCodePrograms = proj.makeCodePrograms.map((x) =>
      x.id === id ? { ...x, name, updatedAt: Date.now() } : x,
    );
  });
}

export function deleteMakeCodeProgram(id: string): void {
  updateProject((proj) => {
    const list = (proj.makeCodePrograms ?? []).filter((x) => x.id !== id);
    proj.makeCodePrograms = list;
    if (proj.currentProgramId === id) {
      proj.currentProgramId = list[list.length - 1]?.id ?? null;
    }
  });
}

/** Update the content of a specific program. Used from the MakeCode onWorkspaceSave hook. */
export function updateMakeCodeProgramFiles(
  id: string,
  files: Record<string, string>,
  header?: unknown,
): void {
  updateProject((proj) => {
    if (!proj.makeCodePrograms) return;
    proj.makeCodePrograms = proj.makeCodePrograms.map((x) =>
      x.id === id
        ? { ...x, files, header: header ?? x.header, updatedAt: Date.now() }
        : x,
    );
  });
}

export function getCurrentMakeCodeProgram(): MakeCodeProgram | null {
  const p = get(currentProject);
  if (!p || !p.currentProgramId) return null;
  return (p.makeCodePrograms ?? []).find((x) => x.id === p.currentProgramId) ?? null;
}

/**
 * True when the program was generated against a different class list, mode, or
 * threshold set than the project currently has — i.e. its baked-in
 * `teachable.ts` / `autogenerated.ts` no longer matches reality. The program
 * still loads as-is (we never rewrite its files on load); this is purely a
 * UI hint so the user can decide whether to create a new starter program.
 * Programs without a snapshot predate this change and are always treated as
 * up-to-date — we don't second-guess old data.
 */
export function isMakeCodeProgramOutdated(program: MakeCodeProgram): boolean {
  const p = get(currentProject);
  if (!p) return false;
  if (!program.classesSnapshot) return false;
  const a = program.classesSnapshot;
  const b = p.classes ?? [];
  if (a.length !== b.length) return true;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) return true;
  }
  if (program.modeSnapshot && program.modeSnapshot !== p.mode) return true;
  const ta = program.thresholdsSnapshot ?? {};
  const tb = p.classThresholds ?? {};
  for (const cls of b) {
    const va = ta[cls];
    const vb = tb[cls];
    if ((va ?? null) !== (vb ?? null)) return true;
  }
  return false;
}

export function setClassThreshold(cls: string, threshold: number): void {
  updateProject((p) => {
    p.classThresholds = { ...(p.classThresholds || {}), [cls]: threshold };
  });
}

export function setTrainedModelRoi(id: string, roi: Roi | null): void {
  updateProject((p) => {
    p.modelHistory = p.modelHistory.map((m) =>
      m.id === id ? { ...m, roi: roi ?? undefined } : m
    );
  });
}

function summarize(p: Project): ProjectSummary {
  return {
    id: p.id,
    name: p.name,
    mode: p.mode ?? 'image',
    createdAt: p.createdAt,
    updatedAt: p.updatedAt,
    classCount: p.classes.length,
    hasModel: !!p.modelArtifacts
  };
}

export const currentProject = writable<Project | null>(null);
export const projectList = writable<ProjectSummary[]>([]);

export const hasProject = derived(currentProject, (p) => p !== null);

/**
 * The training run the project currently points at, or null when nothing is
 * selected (or the loaded classifier came from an imported ZIP, which has no
 * history entry). Everything a selected model should describe — its classes,
 * example counts, accuracy, ROI — lives on this snapshot, not on the project's
 * live class list, which keeps changing while the user records new material.
 */
export const activeModel = derived(currentProject, (p): TrainedModel | null => {
  if (!p?.currentModelId) return null;
  return p.modelHistory?.find((m) => m.id === p.currentModelId) ?? null;
});

export async function refreshProjectList(): Promise<void> {
  const all = await idbGetAll<Project>(STORES.projects);
  const summaries = all.map((p) => summarize(hydrate(p))).sort((a, b) => b.updatedAt - a.updatedAt);
  projectList.set(summaries);
}

let saveTimer: ReturnType<typeof setTimeout> | null = null;

export function scheduleSave(): void {
  if (saveTimer) clearTimeout(saveTimer);
  saveTimer = setTimeout(() => {
    void saveCurrentProject();
  }, 400);
}

export async function saveCurrentProject(): Promise<void> {
  const p = get(currentProject);
  if (!p) return;
  p.updatedAt = Date.now();
  await idbPut(STORES.projects, p);
  await refreshProjectList();
}

export async function loadProject(id: string): Promise<Project | null> {
  const raw = await idbGet<Project>(STORES.projects, id);
  if (!raw) return null;
  const p = hydrate(raw);
  currentProject.set(p);
  try {
    localStorage.setItem(LAST_PROJECT_KEY, id);
  } catch {
    /* ignore */
  }
  return p;
}

export async function newProject(name?: string, mode: ProjectMode = 'image'): Promise<Project> {
  const p = createBlankProject(name, mode);
  await idbPut(STORES.projects, p);
  currentProject.set(p);
  try {
    localStorage.setItem(LAST_PROJECT_KEY, p.id);
  } catch {
    /* ignore */
  }
  await refreshProjectList();
  return p;
}

export async function deleteProject(id: string): Promise<void> {
  await idbDelete(STORES.projects, id);
  const curr = get(currentProject);
  if (curr?.id === id) {
    closeCurrentProject();
  }
  await refreshProjectList();
}

export function closeCurrentProject(): void {
  currentProject.set(null);
  try {
    localStorage.removeItem(LAST_PROJECT_KEY);
  } catch {
    /* ignore */
  }
}

export async function renameCurrentProject(name: string): Promise<void> {
  currentProject.update((p) => (p ? { ...p, name } : p));
  await saveCurrentProject();
}

export function getLastProjectId(): string | null {
  try {
    return localStorage.getItem(LAST_PROJECT_KEY);
  } catch {
    return null;
  }
}

export function recordTrainedModel(
  artifacts: ModelArtifacts,
  metadata: ModelMetadata,
  history: TrainingHistory,
  options: TrainingOptions,
  classesSnapshot: string[],
  exampleCounts: Record<string, number>,
  extras?: { roi?: Roi; featureExtractor?: FeatureExtractor }
): string | null {
  const id = `mdl_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 6)}`;
  let created: string | null = null;
  updateProject((p) => {
    const next = [
      ...p.modelHistory,
      {
        id,
        trainedAt: Date.now(),
        artifacts,
        metadata,
        history,
        options,
        classesSnapshot,
        exampleCounts,
        ...(extras?.roi ? { roi: extras.roi } : {}),
        ...(extras?.featureExtractor ? { featureExtractor: extras.featureExtractor } : {})
      }
    ];
    // Cap history at 20 most recent runs to keep storage bounded
    p.modelHistory = next.length > 20 ? next.slice(-20) : next;
    p.currentModelId = id;
    created = id;
  });
  return created;
}

export function setCurrentModel(id: string): TrainedModel | null {
  let chosen: TrainedModel | null = null;
  updateProject((p) => {
    const m = p.modelHistory.find((x) => x.id === id);
    if (!m) return;
    p.currentModelId = id;
    p.modelArtifacts = m.artifacts;
    p.modelMetadata = m.metadata;
    p.trainingHistory = m.history;
    p.trainingOptions = m.options;
    chosen = m;
  });
  return chosen;
}

export function deleteTrainedModel(id: string): void {
  updateProject((p) => {
    p.modelHistory = p.modelHistory.filter((m) => m.id !== id);
    if (p.currentModelId === id) {
      const last = p.modelHistory[p.modelHistory.length - 1];
      if (last) {
        p.currentModelId = last.id;
        p.modelArtifacts = last.artifacts;
        p.modelMetadata = last.metadata;
        p.trainingHistory = last.history;
      } else {
        p.currentModelId = null;
        p.modelArtifacts = null;
        p.trainingHistory = { epochs: [], accuracy: [], loss: [] };
      }
    }
  });
}

export function renameTrainedModel(id: string, label: string): void {
  updateProject((p) => {
    const trimmed = label.trim();
    p.modelHistory = p.modelHistory.map((m) =>
      m.id === id ? { ...m, label: trimmed || undefined } : m
    );
  });
}

export function updateProject(mutator: (p: Project) => void): void {
  currentProject.update((p) => {
    if (!p) return p;
    mutator(p);
    return p;
  });
  scheduleSave();
}

export async function importProjectFromJson(data: Project): Promise<Project> {
  const p: Project = {
    ...createBlankProject(data.name, data.mode ?? 'image'),
    classes: data.classes || [],
    examples: data.examples || {},
    activeClass: data.activeClass || null,
    trainingOptions: {
      ...DEFAULT_TRAINING_OPTIONS,
      ...(data.trainingOptions || {}),
      featureExtractor: resolveFeatureExtractor(data.trainingOptions?.featureExtractor)
    },
    trainingHistory: data.trainingHistory || { epochs: [], accuracy: [], loss: [] },
    modelMetadata: data.modelMetadata || {
      name: data.name,
      date: new Date().toISOString(),
      version: '1.0',
      classes: data.classes || []
    },
    modelArtifacts: data.modelArtifacts || null,
    modelHistory: data.modelHistory || [],
    currentModelId: data.currentModelId ?? null
  };
  await idbPut(STORES.projects, p);
  currentProject.set(p);
  try {
    localStorage.setItem(LAST_PROJECT_KEY, p.id);
  } catch {
    /* ignore */
  }
  await refreshProjectList();
  return p;
}
