<script lang="ts">
  import { onMount } from 'svelte';
  import { classes, addClass, examples, activeClass, setActiveClass, pushExample, clearClass, videoRefs, modelMetadata, trainingHistory } from '$lib/stores';
  import { showNotification } from '$lib/stores/notifications';
  import Thumbs from '$lib/components/Thumbs.svelte';
  import ImportDialog from '$lib/components/ImportDialog.svelte';
  import { pressHold } from '$lib/actions/pressHold';
  import ModelDetailsDialog from '$lib/components/ModelDetailsDialog.svelte';
  import { classifierModel } from '$lib/stores';
  import { trainModel, captureFrameFromVideo, processZipFile, downloadClassImages, downloadAllClassImages, loadModelFromZip, saveModelToZip } from '$lib/machine';
  import { generateMakeCodeProject, importProject, downloadMakeCodeProject } from '$lib/makecode';
  import { get } from 'svelte/store';

  let newClassName = '';
  let epochs = 20;
  let isCapturing = false;
  let captureRate = 80; // 6 images/sec ≈ 167ms -> legacy uses 80ms for ~12.5fps maybe we'll use 166

  function createClass() {
    if (!newClassName.trim()) return;
    addClass(newClassName.trim());
    newClassName = '';
  }

  function setActive(name: string) {
    setActiveClass(name);
  }

  function startCapture() {
    if (!get(activeClass)) { showNotification('Bitte zuerst eine Klasse wählen', { type: 'warning' }); return; }
    const vid = get(videoRefs).webcam;
    if (!vid) { showNotification('Kamera nicht verbunden', { type: 'error' }); return; }
    // Capture a single frame immediately. When holding, the pressHold action will call this repeatedly.
    const data = captureFrameFromVideo(vid);
    pushExample(get(activeClass)!, data);
    isCapturing = true;
  }

  function stopCapture() {
    isCapturing = false;
  }

    let detailsOpen = false;
  async function doTrain() {
    try {
      await trainModel(epochs, (e, logs) => {
        // optional: update UI
        console.log('Epoch', e, logs);
      });
      showNotification('Training abgeschlossen', { type: 'success' });
      // After training, create MakeCode project with autogenerated files and import into MakeCode iframe
      try {
        const cls = get(classes);
        const exs = get(examples);
        const project = generateMakeCodeProject('Teachable Project', cls, exs);
        importProject(project);
      } catch (err) {
        console.warn('Could not import project to MakeCode', err);
      }
    } catch (err) {
      console.error('Training failed', err);
      showNotification('Fehler beim Training: ' + (err as Error).message, { type: 'error' });
    }
  }

  let filesInput: HTMLInputElement | null = null;
  let importProjectInput: HTMLInputElement | null = null;
  let modelInfo = '';

  $: {
    const m = get(modelMetadata);
    if (m) modelInfo = `${m.name || ''} - ${m.date ? new Date(m.date).toLocaleString() : ''}`;
  }
  // Import dialog related
  let importDialogOpen = false;
  let importDialogImages: string[] = [];
  let importDetectedClass: string | null = null;
  async function onFilesChange(e: Event) {
    const target = e.target as HTMLInputElement;
    const files = target.files;
    if (!files?.length) return;
    if (!get(activeClass)) { showNotification('Bitte wähle zuerst eine Klasse aus', { type: 'warning' }); target.value = ''; return; }
    for (let i = 0; i < files.length; i++) {
      const file = files[i];
      if (file.name.endsWith('.zip')) {
        try {
          const result = await processZipFile(file);
          const imgDataUrls = result.images || [];
          const detectedClass = result.detectedClass;
          const knownClasses = get(classes);
          if (detectedClass && knownClasses.includes(detectedClass)) {
            for (const url of imgDataUrls) pushExample(detectedClass, url);
          } else if (get(activeClass) && (!detectedClass || imgDataUrls.length > 0)) {
            // add to currently selected class if applicable
            for (const url of imgDataUrls) pushExample(get(activeClass)!, url);
          } else {
            importDialogImages = imgDataUrls;
            importDetectedClass = detectedClass || null;
            importDialogOpen = true;
          }
        } catch (err) {
          console.error('Zip processing failed', err);
          showNotification('Fehler beim Verarbeiten des Zip-Archivs: ' + ((err as Error)?.message || err), { type: 'error' });
        }
      } else {
        const reader = new FileReader();
        reader.onload = ev => {
          const result = ev.target?.result as string;
          pushExample(get(activeClass)!, result);
        };
        reader.readAsDataURL(file);
      }
    }
    target.value = '';
  }

  function onImportDialogConfirm(e: CustomEvent<{ images: string[]; selectedClass: string | null }>) {
    const { images, selectedClass } = e.detail;
    if (selectedClass) {
      for (const im of images) pushExample(selectedClass, im);
      setActiveClass(selectedClass);
      showNotification(`Importiert ${images.length} Bilder in Klasse ${selectedClass}`, { type: 'success' });
    }
    importDialogOpen = false;
    importDialogImages = [];
    importDetectedClass = null;
  }

  function onImportDialogCancel() {
    importDialogOpen = false;
    importDialogImages = [];
    importDetectedClass = null;
  }

  async function onImportProjectChange(e: Event) {
    const target = e.target as HTMLInputElement;
    if (!target.files?.length) return;
    const file = target.files[0];
    try {
      const JSZip = (await import('jszip')).default;
      const zip = await JSZip.loadAsync(await file.arrayBuffer());
      const files: Record<string, string> = {};
      for (const path of Object.keys(zip.files)) {
        const f = zip.files[path];
        if (f.dir) continue;
        // read as utf8 string
        try {
          const txt = await f.async('string');
          const name = path.split('/').pop() || path;
          files[name] = txt;
        } catch (err) {
          // binary file like weights.bin - ignore
        }
      }
      // we now try to import as a project using MakeCode import
      importProject({ header: { name: file.name }, files });
    } catch (err) {
      console.error('Failed to import project zip', err);
      showNotification('Fehler beim Importieren des Projekts', { type: 'error' });
    }
    target.value = '';
  }

  async function onLoadModelChange(e: Event) {
    const target = e.target as HTMLInputElement;
    if (!target.files?.length) return;
    const file = target.files[0];
    try {
      await loadModelFromZip(file);
      modelInfo = 'Modell geladen';
    } catch (err) {
      console.error('Failed to load model', err);
      modelInfo = 'Fehler beim Laden des Modells';
    }
    target.value = '';
  }

  async function onSaveModel() {
    const model = get(classifierModel);
    if (!model) { showNotification('Kein Modell vorhanden', { type: 'warning' }); return; }
    try {
      await saveModelToZip(model, get(modelMetadata));
    } catch (err) {
      console.error('Saving model failed', err);
      showNotification('Fehler beim Speichern des Modells', { type: 'error' });
    }
  }
</script>

<div class="left-panel panel">
  <h1>Bildprojekt</h1>
  <div>
      <label for="new-class-name">Neue Klasse:</label>
    <div style="display:flex;gap:6px;margin-top:4px;">
      <input id="new-class-name" type="text" placeholder="z. B. Hand" bind:value={newClassName} />
      <button class="create-class" on:click={createClass}>+</button>
    </div>
  </div>
{#if $classes.length > 0}
  <div style="margin-top:10px;">
      <label for="class-list">Klassen:</label>
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:4px;">
      <span style="font-size:12px;color:#666;">Klick zum Auswählen</span>
      <button class="download-all ghost" style="font-size:12px;padding:4px 8px;" on:click={() => downloadAllClassImages($examples)}>Alle herunterladen</button>
    </div>
      <div class="class-list" style="margin-top:4px;">
        {#each $classes as c}
          <div
            role="button"
            tabindex="0"
            class="class-item {c === $activeClass ? 'selected' : ''}"
            on:click={() => setActive(c)}
            on:keydown={(e) => { if (e.key === 'Enter' || e.key === ' ') setActive(c); }}
          >
            <span class="class-name">{c} ({$examples[c]?.length || 0})</span>
            <div class="class-actions">
              <button type="button" class="ghost" title="Bilder herunterladen" on:click|stopPropagation={() => downloadClassImages(c, $examples[c] || [])}>↓</button>
            </div>
          </div>
        {/each}
      </div>
  </div>

  <hr style="margin:12px 0;">

  <div>
    {#if $activeClass}
      <label for="active-class">Aktive Klasse: {$activeClass}</label>
    <div style="margin-top:8px;display:flex;gap:6px;">
      <button class="primary-action capture" use:pressHold={{ onStart: startCapture, onEnd: stopCapture, interval: captureRate }} class:active={isCapturing}>{isCapturing ? 'Aufnahme läuft' : 'Aufnahme starten'}</button>
      <label class="file-label" for="file-input">
        Dateien
        <input id="file-input" type="file" accept="image/*,.zip" style="display:none" multiple bind:this={filesInput} on:change={onFilesChange}>
      </label>
      <button class="ghost clear-class" on:click={() => { if ($activeClass) clearClass($activeClass); }}>Leeren</button>
    </div>
    <div class="button-hint capture-hint">Halte die Taste gedrückt, um Bilder aufzunehmen</div>
      <div class="capture-count" style="margin-top:6px;font-size:13px;color:#555;">{ $activeClass ? ($examples[$activeClass]?.length || 0) : 0 } Bilder</div>

    <Thumbs />
    {:else}
      <div style="font-size:13px;color:#666;margin-top:6px;">Keine Klasse ausgewählt</div>
    {/if}
  </div>

  <hr style="margin:12px 0;">

  <div class:disabled={ $classes.length < 2 } class="training-section">
      <label for="epochs">Training:</label>
    <div style="display:flex;gap:8px;margin-top:6px;">
      <input id="epochs" type="number" bind:value={epochs} min="1" style="width:80px;" />
      <button class="train" on:click={doTrain}>Modell Trainieren</button>
      <button class="model-details ghost" on:click={() => detailsOpen = true} disabled={$classifierModel == null}>Modell Details</button>
    </div>
    <div class="status light train-status" style="margin-top:6px;color:#007acc;">Bereit</div>
    <!-- Model summary: show basic model metadata here for quick glance -->
    <div class="model-summary" style="display:flex;flex-wrap:wrap;gap:8px;margin-top:8px;align-items:center;">
      <div class="small-stat">{modelInfo}</div>
      <div class="small-stat">Parameter: {$modelMetadata.params ?? '-'}</div>
      <div class="small-stat">Schichten: {$modelMetadata.layers ?? '-'}</div>
      <div class="small-stat">Größe: {$modelMetadata.sizeBytes ? ($modelMetadata.sizeBytes / 1024).toFixed(2) + ' KB' : '-'}</div>
      <div class="small-stat">Genauigkeit: {$trainingHistory.accuracy.length ? (($trainingHistory.accuracy[$trainingHistory.accuracy.length - 1] * 100).toFixed(1) + '%') : '-'}</div>
    </div>
    <ModelDetailsDialog bind:open={detailsOpen} />
  </div>

  <hr style="margin:12px 0;">

  <div>
    <label for="load-model">Modell:</label>
    <div style="display:flex;gap:8px;margin-top:6px;">
      <button class="save-model ghost" on:click={onSaveModel}>Speichern</button>
      <label class="file-label" for="load-model">
        Laden
        <input id="load-model" type="file" accept=".zip" style="display:none" on:change={onLoadModelChange} />
      </label>
    </div>
    <div class="model-info">{modelInfo}</div>
  </div>

  <div class="project-buttons">
    <button class="download-project" on:click={async () => {
      // generate or download makecode project
      const cls = get(classes);
      if (!cls.length) { showNotification('Keine Klassen enthalten - Projekt kann nicht generiert werden', { type: 'warning' }); return; }
      try {
        const exs = get(examples);
        await downloadMakeCodeProject('Teachable Project', cls, exs);
        showNotification('MakeCode Projekt heruntergeladen', { type: 'success' });
      } catch (err) {
        console.error(err);
        showNotification('Fehler beim Herunterladen des Projekts', { type: 'error' });
      }
    }}>Projekt herunterladen</button>
      <label class="file-label" for="import-project">
      Projekt importieren
      <input id="import-project" type="file" accept=".zip" style="display:none" bind:this={importProjectInput} on:change={onImportProjectChange} />
    </label>
  </div>
  {:else}
    <div style="font-size:13px;color:#666;margin-top:12px;">Keine Klassen vorhanden. Bitte erstelle eine Klasse, um Bilder hinzuzufügen und das Modell zu trainieren.</div>
  {/if}
  <ImportDialog bind:open={importDialogOpen} images={importDialogImages} detectedClass={importDetectedClass} on:confirm={onImportDialogConfirm} on:cancel={onImportDialogCancel} />
</div>


<style>

  .training-section.disabled {
    opacity: 0.5;
    pointer-events: none;
  }
</style>