<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { get } from 'svelte/store';
  import {
    initSharedCamera,
    predictFromVideo,
    estimatePose,
    drawPoseSkeleton,
    setLastPoseCanvas,
  } from '$lib/machine';
  import {
    setVideoRef,
    classes,
    mobilenetModel,
    classifierModel,
  } from '$lib/stores';
  import { selectedCameraId } from '$lib/stores/camera';
  import { currentProject } from '$lib/stores/projects';
  import { calliopeState, sendSerialLine } from '$lib/stores/connection';
  import { currentLang, t } from '$lib/stores/app';
  import CameraSelect from '$lib/components/CameraSelect.svelte';

  const CLASS_THRESHOLD = 0.7;
  const TICK_MS = 100; // ~10 Hz for predict + pose.
  const HEARTBEAT_MS = 1000;

  let videoEl: HTMLVideoElement | null = $state(null);
  let skeletonCanvas: HTMLCanvasElement | null = $state(null);

  let currentLabel = $state('');
  let currentConfidence = $state(0);
  let lastSentClassId = -1;
  let lastSentAt = $state(0);

  let tickTimer: ReturnType<typeof setTimeout> | null = null;
  let heartbeatTimer: ReturnType<typeof setInterval> | null = null;
  let tickInFlight = false;
  let disposed = false;

  const lang = $derived($currentLang);
  const mode = $derived($currentProject?.mode ?? 'image');
  const status = $derived($calliopeState.status);
  const connected = $derived(status === 'connected' || status === 'flashing');
  const modelReady = $derived(!!$classifierModel && !!$mobilenetModel);
  // Lit up if we sent something in the last ~2s (heartbeat or classification).
  const sendingNow = $derived(connected && Date.now() - lastSentAt < 2000);

  async function tick() {
    if (disposed || tickInFlight) return;
    tickInFlight = true;
    try {
      if (!videoEl || !videoEl.videoWidth) return;

      if (mode === 'pose') {
        try {
          const pose = await estimatePose(videoEl);
          if (skeletonCanvas) {
            drawPoseSkeleton(
              skeletonCanvas,
              pose,
              videoEl.videoWidth,
              videoEl.videoHeight,
              { size: 224 },
            );
            setLastPoseCanvas(skeletonCanvas);
          }
          if (connected && pose?.keypoints?.length) {
            sendPoseFrame(pose.keypoints, videoEl.videoWidth, videoEl.videoHeight);
          }
        } catch {
          /* swallow — next tick will retry */
        }
      }

      if (modelReady) {
        const p = await predictFromVideo(videoEl);
        if (p) {
          currentLabel = p.className;
          currentConfidence = p.probability;
          if (connected) sendClassification(p.index, p.probability);
        }
      }
    } finally {
      tickInFlight = false;
      if (!disposed) tickTimer = setTimeout(() => void tick(), TICK_MS);
    }
  }

  function sendClassification(idx: number, prob: number) {
    if (prob < CLASS_THRESHOLD) return;
    const id = idx + 1; // autogenerated.ts IDs are 1-based.
    if (id === lastSentClassId) return;
    lastSentClassId = id;
    const conf = Math.round(Math.max(0, Math.min(1, prob)) * 100);
    void sendSerialLine(`C ${id} ${conf}`);
    lastSentAt = Date.now();
  }

  function sendPoseFrame(
    kps: { x: number; y: number; score?: number }[],
    srcW: number,
    srcH: number,
  ) {
    if (!srcW || !srcH) return;
    const parts: string[] = ['P'];
    const n = Math.min(kps.length, 17);
    for (let i = 0; i < 17; i++) {
      const kp = i < n ? kps[i] : undefined;
      if (!kp) {
        parts.push('0', '0', '0');
      } else {
        const x = Math.max(0, Math.min(100, Math.round((kp.x / srcW) * 100)));
        const y = Math.max(0, Math.min(100, Math.round((kp.y / srcH) * 100)));
        const v = (kp.score ?? 0) > 0.3 ? 1 : 0;
        parts.push(String(x), String(y), String(v));
      }
    }
    void sendSerialLine(parts.join(' '));
    lastSentAt = Date.now();
  }

  function startHeartbeat() {
    if (heartbeatTimer) return;
    heartbeatTimer = setInterval(() => {
      if (!connected) return;
      void sendSerialLine('H');
      lastSentAt = Date.now();
    }, HEARTBEAT_MS);
  }

  function stopAllLoops() {
    if (tickTimer) {
      clearTimeout(tickTimer);
      tickTimer = null;
    }
    if (heartbeatTimer) {
      clearInterval(heartbeatTimer);
      heartbeatTimer = null;
    }
    setLastPoseCanvas(null);
  }

  onMount(async () => {
    setVideoRef('webcamTryout', videoEl);
    await initSharedCamera(
      { webcamTryout: videoEl },
      get(selectedCameraId) ?? undefined,
    );
    void tick();
    startHeartbeat();
  });

  onDestroy(() => {
    disposed = true;
    stopAllLoops();
  });

  const labelForMode = $derived(
    mode === 'pose' ? t('welcome.modePose', lang) : t('welcome.modeImage', lang),
  );
</script>

<div class="tryout-camera">
  <div class="camera-header">
    <div class="title">
      <span class="mode-chip mode-{mode}">{labelForMode}</span>
      <span class="class-count">
        {$classes.length}
        {$classes.length === 1 ? 'Klasse' : 'Klassen'}
      </span>
    </div>
    <div class="stream-status" class:live={sendingNow} class:off={!connected}>
      <span class="dot"></span>
      {#if !connected}
        {t('tryout.notConnected', lang)}
      {:else if mode === 'pose'}
        Pose-Stream
      {:else}
        Klassifikationen
      {/if}
    </div>
  </div>

  <div class="camera-tools">
    <CameraSelect />
  </div>

  <div class="video-wrap">
    <video bind:this={videoEl} autoplay playsinline muted>
      <track kind="captions" />
    </video>
    {#if currentLabel}
      <div class="prediction-overlay" class:confident={currentConfidence >= CLASS_THRESHOLD}>
        <div class="pred-label">{currentLabel}</div>
        <div class="pred-bar">
          <div class="pred-bar-fill" style="width: {(currentConfidence * 100).toFixed(0)}%"></div>
        </div>
        <div class="pred-confidence">{(currentConfidence * 100).toFixed(0)}%</div>
      </div>
    {:else if !modelReady}
      <div class="hint">Kein Modell geladen — bitte zuerst trainieren.</div>
    {/if}
  </div>

  <!-- Offscreen: skeleton canvas used by pose mode as predictor input. -->
  {#if mode === 'pose'}
    <canvas bind:this={skeletonCanvas} width="224" height="224" class="offscreen"></canvas>
  {/if}
</div>

<style lang="scss">
  .tryout-camera {
    display: flex;
    flex-direction: column;
    gap: 10px;
    padding: 14px;
    height: 100%;
    min-height: 0;
    overflow: auto;
  }
  .camera-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 10px;
  }
  .title {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 13px;
    color: #555;
  }
  .mode-chip {
    padding: 2px 8px;
    border-radius: 999px;
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.04em;
    text-transform: uppercase;
    background: rgba(0, 0, 0, 0.08);
    color: #1b1c1d;
    &.mode-pose {
      background: #00e5ff;
      color: #003040;
    }
  }
  .class-count {
    color: #888;
    font-size: 12px;
  }
  .stream-status {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    font-size: 12px;
    padding: 4px 10px;
    border-radius: 999px;
    background: rgba(34, 197, 94, 0.1);
    color: #15803d;

    .dot {
      width: 8px;
      height: 8px;
      border-radius: 50%;
      background: #22c55e;
    }
    &.live .dot {
      animation: pulse 1s ease-in-out infinite;
    }
    &.off {
      background: rgba(0, 0, 0, 0.06);
      color: #888;
      .dot { background: #aaa; }
    }
  }
  @keyframes pulse {
    0%, 100% { opacity: 1; }
    50% { opacity: 0.35; }
  }
  .video-wrap {
    position: relative;
    width: 100%;
    padding-top: 75%;
    background: #000;
    border-radius: 10px;
    overflow: hidden;

    video {
      position: absolute;
      inset: 0;
      width: 100%;
      height: 100%;
      object-fit: cover;
    }
  }
  .prediction-overlay {
    position: absolute;
    left: 10px;
    right: 10px;
    bottom: 10px;
    padding: 10px 12px;
    background: rgba(0, 0, 0, 0.55);
    color: #fff;
    border-radius: 8px;
    backdrop-filter: blur(4px);
    display: flex;
    align-items: center;
    gap: 10px;

    .pred-label {
      font-weight: 600;
      flex: 0 0 auto;
      max-width: 55%;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }
    .pred-bar {
      flex: 1 1 auto;
      height: 6px;
      background: rgba(255, 255, 255, 0.18);
      border-radius: 3px;
      overflow: hidden;
    }
    .pred-bar-fill {
      height: 100%;
      background: #9ca3af;
      transition: width 0.15s;
    }
    .pred-confidence {
      font-variant-numeric: tabular-nums;
      font-size: 12px;
      opacity: 0.85;
      flex: 0 0 auto;
    }
    &.confident .pred-bar-fill {
      background: #22c55e;
    }
  }
  .hint {
    position: absolute;
    inset: 0;
    display: grid;
    place-items: center;
    color: rgba(255, 255, 255, 0.65);
    font-size: 13px;
    text-align: center;
    padding: 20px;
  }
  .offscreen {
    position: absolute;
    left: -9999px;
    width: 1px;
    height: 1px;
  }
</style>
