/**
 * Downloads the Inter webfont into `static/fonts/` and writes the matching
 * @font-face CSS. Committed output; run with `node scripts/vendor-fonts.mjs`.
 *
 * Self-hosted so the app makes no request to fonts.googleapis.com — that request
 * is blocking, leaks visitor IPs to a third party (a problem for a product used
 * in schools), and fails in offline or filtered networks.
 *
 * We ship the variable font (wght 100..900), so all weights come from one file
 * per subset instead of one per weight.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'static', 'fonts');
const CSS_URL = 'https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap';
// Google serves woff2 + variable ranges only to browsers it recognises.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';
const WANTED = ['latin', 'latin-ext'];

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

// Each @font-face block is preceded by a /* subset */ comment.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)];
const out = [
  '/* Inter — self-hosted, generated by scripts/vendor-fonts.mjs. Do not edit by hand. */',
  '/* Inter is licensed under the SIL Open Font License 1.1, see static/fonts/LICENSE. */'
];

for (const [, subset, body] of blocks) {
  if (!WANTED.includes(subset)) continue;
  const url = body.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  if (!url) continue;
  const file = `inter-${subset}.woff2`;
  const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
  await mkdir(OUT, { recursive: true });
  await writeFile(join(OUT, file), buf);
  const unicodeRange = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
  out.push(
    '',
    `/* ${subset} */`,
    '@font-face {',
    "  font-family: 'Inter';",
    '  font-style: normal;',
    '  font-weight: 100 900;',
    '  font-display: swap;',
    // Relative to this stylesheet, so it survives being served under a base path.
    `  src: url('./${file}') format('woff2');`,
    ...(unicodeRange ? [`  unicode-range: ${unicodeRange};`] : []),
    '}'
  );
  console.log(`${file.padEnd(24)} ${(buf.length / 1024).toFixed(0).padStart(4)} KB`);
}

if (out.length <= 2) throw new Error('No matching @font-face blocks found — did the Google Fonts CSS format change?');
await writeFile(join(OUT, 'inter.css'), out.join('\n') + '\n');

const license = await (await fetch('https://raw.githubusercontent.com/rsms/inter/master/LICENSE.txt')).text();
await writeFile(join(OUT, 'LICENSE'), license);
console.log('inter.css + LICENSE geschrieben');
