// The contents of `teachable.ts` that ships inside every generated MakeCode
// project. This is the block API the student programs against. The app streams
// ASCII lines over serial (WebUSB / WebBLE UART) and the extension parses them.
//
// Wire protocol (newline-terminated):
//   C <c1> <c2> ... <cN>                     — confidences for ALL classes (0–100)
//                                              The board decides when to fire the
//                                              per-class event using thresholds.
//   P <x0> <y0> <v0> <x1> <y1> <v1> ...      — pose frame (17 keypoints, 0–100)
//   H                                        — heartbeat

export function teachableExtensionSource(mode: 'image' | 'pose'): string {
  const common = `
/**
 * Teachable Calliope — blocks for classes trained in the Teachable Calliope app.
 */
//% color="#CC4B00" weight=100 icon="\\uf06e" block="Teachable"
//% groups='["Klassen", "Schwellwerte", "Pose"]'
namespace teachable {
    //% fixedInstances
    export class MlClass {
        public id: number;
        public name: string;
        constructor(id: number, name: string) {
            this.id = id;
            this.name = name;
        }
    }

    // Populated by autogenerated.ts (one entry per trained class).
    export const classRegistry: MlClass[] = [];

    let currentId = 0;
    const confidences: number[] = [];
    const thresholds: number[] = [];
    // Populated by autogenerated.ts with the thresholds the user set in the
    // Teachable app's training view. resetThreshold() restores these.
    export const defaultThresholds: number[] = [];
    const FALLBACK_THRESHOLD = 60;
    const handlers: (() => void)[] = [];
    let anyHandler: ((cls: MlClass) => void) | undefined = undefined;
    let lastHeartbeatMs = 0;

    function resolveDefault(id: number): number {
        const d = defaultThresholds[id];
        return d === undefined ? FALLBACK_THRESHOLD : d;
    }

    //% block="set threshold of %cls to %percent \\\\%" group="Schwellwerte"
    //% blockId=teachable_set_threshold
    //% percent.min=0 percent.max=100 percent.defl=60
    //% weight=72
    export function setThreshold(cls: MlClass, percent: number): void {
        if (!cls) return;
        if (percent < 0) percent = 0;
        if (percent > 100) percent = 100;
        thresholds[cls.id] = percent;
    }

    //% block="reset threshold of %cls" group="Schwellwerte"
    //% blockId=teachable_reset_threshold
    //% weight=73
    export function resetThreshold(cls: MlClass): void {
        if (!cls) return;
        thresholds[cls.id] = resolveDefault(cls.id);
    }

    //% block="threshold of %cls" group="Schwellwerte"
    //% blockId=teachable_get_threshold
    //% weight=71
    export function getThreshold(cls: MlClass): number {
        if (!cls) return FALLBACK_THRESHOLD;
        const t = thresholds[cls.id];
        return t === undefined ? resolveDefault(cls.id) : t;
    }

    //% block="when %cls is detected" group="Klassen"
    //% blockId=teachable_on_class
    //% weight=90
    export function onClass(cls: MlClass, handler: () => void): void {
        if (!cls) return;
        handlers[cls.id] = handler;
    }

    //% block="on any class detected" group="Klassen"
    //% blockId=teachable_on_any
    //% draggableParameters=reporter
    //% weight=85
    export function onAnyClass(handler: (detected: MlClass) => void): void {
        anyHandler = handler;
    }

    //% block="detected class" group="Klassen"
    //% blockId=teachable_current_class
    //% weight=80
    export function currentClass(): MlClass {
        return classRegistry[currentId] || classRegistry[0];
    }

    //% block="detected class is %cls" group="Klassen"
    //% blockId=teachable_is_class
    //% weight=78
    export function isClass(cls: MlClass): boolean {
        if (!cls) return false;
        return currentId === cls.id;
    }

    //% block="confidence of %cls" group="Klassen"
    //% blockId=teachable_confidence
    //% weight=75
    export function confidence(cls: MlClass): number {
        if (!cls) return 0;
        return confidences[cls.id] | 0;
    }

    //% block="connected to Teachable app" group="Klassen"
    //% blockId=teachable_connected
    //% weight=70
    export function isConnected(): boolean {
        return control.millis() - lastHeartbeatMs < 3000;
    }
`;

  const poseBlocks = `
    // --- Pose mode ---

    export enum BodyPart {
        //% block="nose"
        Nose = 0,
        //% block="left eye"
        LeftEye = 1,
        //% block="right eye"
        RightEye = 2,
        //% block="left ear"
        LeftEar = 3,
        //% block="right ear"
        RightEar = 4,
        //% block="left shoulder"
        LeftShoulder = 5,
        //% block="right shoulder"
        RightShoulder = 6,
        //% block="left elbow"
        LeftElbow = 7,
        //% block="right elbow"
        RightElbow = 8,
        //% block="left wrist"
        LeftWrist = 9,
        //% block="right wrist"
        RightWrist = 10,
        //% block="left hip"
        LeftHip = 11,
        //% block="right hip"
        RightHip = 12,
        //% block="left knee"
        LeftKnee = 13,
        //% block="right knee"
        RightKnee = 14,
        //% block="left ankle"
        LeftAnkle = 15,
        //% block="right ankle"
        RightAnkle = 16
    }

    const KP_COUNT = 17;
    const kpX: number[] = [];
    const kpY: number[] = [];
    const kpVis: number[] = [];
    let poseHandler: (() => void) | undefined = undefined;

    //% block="x of %part" group="Pose"
    //% blockId=teachable_body_x
    //% weight=60
    export function bodyPartX(part: BodyPart): number {
        return kpX[part] | 0;
    }

    //% block="y of %part" group="Pose"
    //% blockId=teachable_body_y
    //% weight=59
    export function bodyPartY(part: BodyPart): number {
        return kpY[part] | 0;
    }

    //% block="%part is visible" group="Pose"
    //% blockId=teachable_body_visible
    //% weight=58
    export function isVisible(part: BodyPart): boolean {
        return (kpVis[part] | 0) > 0;
    }

    //% block="distance between %a and %b" group="Pose"
    //% blockId=teachable_distance
    //% weight=57
    export function distanceBetween(a: BodyPart, b: BodyPart): number {
        const dx = (kpX[a] | 0) - (kpX[b] | 0);
        const dy = (kpY[a] | 0) - (kpY[b] | 0);
        return Math.sqrt(dx * dx + dy * dy) | 0;
    }

    //% block="on pose frame" group="Pose"
    //% blockId=teachable_on_pose
    //% weight=56
    export function onPoseFrame(handler: () => void): void {
        poseHandler = handler;
    }

    function parsePoseFrame(rest: string) {
        const parts = rest.split(" ");
        const count = Math.min(Math.idiv(parts.length, 3), KP_COUNT);
        for (let i = 0; i < count; i++) {
            kpX[i] = parseInt(parts[i * 3]);
            kpY[i] = parseInt(parts[i * 3 + 1]);
            kpVis[i] = parseInt(parts[i * 3 + 2]);
        }
        if (poseHandler) poseHandler();
    }
`;

  const parser = `
    function fireClassEvent(id: number) {
        if (id === currentId) return;
        currentId = id;
        const h = handlers[id];
        if (h) h();
        const cls = classRegistry[id];
        if (anyHandler && cls) anyHandler(cls);
    }

    function handleAllConfidences(rest: string) {
        // Parse space-separated confidences (0..100) for class ids 1..N and
        // pick the winner by threshold-normalized headroom: for each class,
        // remap [threshold..100] -> [0..100] and pick the largest. This way a
        // class with a low threshold (e.g. 5%) currently at 20% beats a class
        // with a high threshold (e.g. 70%) currently at 60%.
        const parts = rest.split(" ");
        let topId = 0;
        let topNorm = 0;
        for (let i = 0; i < parts.length; i++) {
            const conf = parseInt(parts[i]);
            const id = i + 1;
            confidences[id] = conf;
            const t = thresholds[id];
            const thr = t === undefined ? resolveDefault(id) : t;
            if (conf <= thr || thr >= 100) continue;
            const norm = Math.idiv((conf - thr) * 100, 100 - thr);
            if (norm > topNorm) {
                topNorm = norm;
                topId = id;
            }
        }
        if (topId > 0) fireClassEvent(topId);
    }

    function handleLine(line: string) {
        if (!line || line.length < 1) return;
        const kind = line.charAt(0);
        if (kind === "C") {
            const rest = line.length > 2 ? line.substr(2) : "";
            handleAllConfidences(rest);
            lastHeartbeatMs = control.millis();
        } else if (kind === "H") {
            lastHeartbeatMs = control.millis();
        }${
          mode === 'pose'
            ? ` else if (kind === "P") {
            const rest = line.length > 2 ? line.substr(2) : "";
            parsePoseFrame(rest);
            lastHeartbeatMs = control.millis();
        }`
            : ''
        }
    }

    // Wire up serial. serial.onDataReceived fires per delimiter.
    serial.onDataReceived("\\n", function () {
        const line = serial.readUntil("\\n");
        handleLine(line);
    });
}
`;

  return common + (mode === 'pose' ? poseBlocks : '') + parser;
}
