// The contents of `teachable.ts` that ships inside every generated MakeCode
// project. This is the block API the student programs against. The app streams
// ASCII lines over serial (WebUSB / WebBLE UART) and the extension parses them.
//
// Wire protocol (newline-terminated):
//   C <id> <conf>                            — classification
//   P <x0> <y0> <v0> <x1> <y1> <v1> ...      — pose frame (17 keypoints, 0–100)
//   H                                        — heartbeat

export function teachableExtensionSource(mode: 'image' | 'pose'): string {
  const common = `
/**
 * Teachable Calliope — blocks for classes trained in the Teachable Calliope app.
 */
//% color="#CC4B00" weight=100 icon="\\uf06e" block="Teachable"
namespace teachable {
    //% fixedInstances
    export class MlClass {
        public id: number;
        public name: string;
        constructor(id: number, name: string) {
            this.id = id;
            this.name = name;
        }
    }

    // Populated by autogenerated.ts (one entry per trained class).
    export const classRegistry: MlClass[] = [];

    let currentId = 0;
    const confidences: number[] = [];
    const handlers: (() => void)[] = [];
    let anyHandler: ((cls: MlClass) => void) | undefined = undefined;
    let lastHeartbeatMs = 0;

    //% block="when %cls is detected"
    //% blockId=teachable_on_class
    //% weight=90
    export function onClass(cls: MlClass, handler: () => void): void {
        if (!cls) return;
        handlers[cls.id] = handler;
    }

    //% block="on any class detected"
    //% blockId=teachable_on_any
    //% draggableParameters=reporter
    //% weight=85
    export function onAnyClass(handler: (detected: MlClass) => void): void {
        anyHandler = handler;
    }

    //% block="detected class"
    //% blockId=teachable_current_class
    //% weight=80
    export function currentClass(): MlClass {
        return classRegistry[currentId] || classRegistry[0];
    }

    //% block="detected class is %cls"
    //% blockId=teachable_is_class
    //% weight=78
    export function isClass(cls: MlClass): boolean {
        if (!cls) return false;
        return currentId === cls.id;
    }

    //% block="confidence of %cls"
    //% blockId=teachable_confidence
    //% weight=75
    export function confidence(cls: MlClass): number {
        if (!cls) return 0;
        return confidences[cls.id] | 0;
    }

    //% block="connected to Teachable app"
    //% blockId=teachable_connected
    //% weight=70
    export function isConnected(): boolean {
        return control.millis() - lastHeartbeatMs < 3000;
    }
`;

  const poseBlocks = `
    // --- Pose mode ---

    export enum BodyPart {
        //% block="nose"
        Nose = 0,
        //% block="left eye"
        LeftEye = 1,
        //% block="right eye"
        RightEye = 2,
        //% block="left ear"
        LeftEar = 3,
        //% block="right ear"
        RightEar = 4,
        //% block="left shoulder"
        LeftShoulder = 5,
        //% block="right shoulder"
        RightShoulder = 6,
        //% block="left elbow"
        LeftElbow = 7,
        //% block="right elbow"
        RightElbow = 8,
        //% block="left wrist"
        LeftWrist = 9,
        //% block="right wrist"
        RightWrist = 10,
        //% block="left hip"
        LeftHip = 11,
        //% block="right hip"
        RightHip = 12,
        //% block="left knee"
        LeftKnee = 13,
        //% block="right knee"
        RightKnee = 14,
        //% block="left ankle"
        LeftAnkle = 15,
        //% block="right ankle"
        RightAnkle = 16
    }

    const KP_COUNT = 17;
    const kpX: number[] = [];
    const kpY: number[] = [];
    const kpVis: number[] = [];
    let poseHandler: (() => void) | undefined = undefined;

    //% block="x of %part" group="Pose"
    //% blockId=teachable_body_x
    //% weight=60
    export function bodyPartX(part: BodyPart): number {
        return kpX[part] | 0;
    }

    //% block="y of %part" group="Pose"
    //% blockId=teachable_body_y
    //% weight=59
    export function bodyPartY(part: BodyPart): number {
        return kpY[part] | 0;
    }

    //% block="%part is visible" group="Pose"
    //% blockId=teachable_body_visible
    //% weight=58
    export function isVisible(part: BodyPart): boolean {
        return (kpVis[part] | 0) > 0;
    }

    //% block="distance between %a and %b" group="Pose"
    //% blockId=teachable_distance
    //% weight=57
    export function distanceBetween(a: BodyPart, b: BodyPart): number {
        const dx = (kpX[a] | 0) - (kpX[b] | 0);
        const dy = (kpY[a] | 0) - (kpY[b] | 0);
        return Math.sqrt(dx * dx + dy * dy) | 0;
    }

    //% block="on pose frame" group="Pose"
    //% blockId=teachable_on_pose
    //% weight=56
    export function onPoseFrame(handler: () => void): void {
        poseHandler = handler;
    }

    function parsePoseFrame(rest: string) {
        const parts = rest.split(" ");
        const count = Math.min(Math.idiv(parts.length, 3), KP_COUNT);
        for (let i = 0; i < count; i++) {
            kpX[i] = parseInt(parts[i * 3]);
            kpY[i] = parseInt(parts[i * 3 + 1]);
            kpVis[i] = parseInt(parts[i * 3 + 2]);
        }
        if (poseHandler) poseHandler();
    }
`;

  const parser = `
    function dispatchClass(id: number, conf: number) {
        confidences[id] = conf;
        if (id !== currentId) {
            currentId = id;
            const h = handlers[id];
            if (h) h();
            const cls = classRegistry[id];
            if (anyHandler && cls) anyHandler(cls);
        }
    }

    function handleLine(line: string) {
        if (!line || line.length < 1) return;
        const kind = line.charAt(0);
        if (kind === "C") {
            // "C <id> <conf>"
            const rest = line.length > 2 ? line.substr(2) : "";
            const sp = rest.indexOf(" ");
            if (sp < 0) return;
            const id = parseInt(rest.substr(0, sp));
            const conf = parseInt(rest.substr(sp + 1));
            dispatchClass(id, conf);
            lastHeartbeatMs = control.millis();
        } else if (kind === "H") {
            lastHeartbeatMs = control.millis();
        }${
          mode === 'pose'
            ? ` else if (kind === "P") {
            const rest = line.length > 2 ? line.substr(2) : "";
            parsePoseFrame(rest);
            lastHeartbeatMs = control.millis();
        }`
            : ''
        }
    }

    // Wire up serial. serial.onDataReceived fires per delimiter.
    serial.onDataReceived("\\n", function () {
        const line = serial.readUntil("\\n");
        handleLine(line);
    });
}
`;

  return common + (mode === 'pose' ? poseBlocks : '') + parser;
}
