// The contents of `teachable.ts` that ships inside every generated MakeCode
// project. This is the block API the student programs against. The app streams
// ASCII lines over serial (WebUSB / WebBLE UART) and the extension parses them.
//
// Wire protocol (newline-terminated):
//   D <id> <c1> <c2> ... <cN>                — the detected class (1-based,
//                                              0 = none) followed by the
//                                              confidences for ALL classes
//                                              (0–100), already mapped
//                                              through each class's calibration
//                                              window in the app. One line, so
//                                              the scores a handler reads are
//                                              the ones its class was picked
//                                              from. The app decides the
//                                              winner: the calibration belongs
//                                              to a model, and a program can be
//                                              pointed at another model, so a
//                                              threshold baked in here would go
//                                              stale.
//   C <c1> ... <cN> / W <id>                 — the same thing split over two
//                                              lines, as app versions before
//                                              the D line sent it. Still parsed,
//                                              so a project generated today
//                                              keeps working against an older
//                                              app.
//   P <x0> <y0> <v0> <x1> <y1> <v1> ...      — pose frame (17 keypoints, 0–100)
//   H                                        — heartbeat

export function teachableExtensionSource(mode: 'image' | 'pose'): string {
  const common = `
/**
 * Teachable Calliope — blocks for classes trained in the Teachable Calliope app.
 *
 * Regenerated by the app every time this project is opened — put your own code
 * in main.blocks / main.ts, edits here are lost.
 */
//% color="#CC4B00" weight=100 icon="\\uf06e" block="Teachable"
//% groups='["Klassen", "Pose"]'
namespace teachable {
    //% fixedInstances
    export class MlClass {
        public id: number;
        public name: string;
        constructor(id: number, name: string) {
            this.id = id;
            this.name = name;
        }
    }

    // Populated by autogenerated.ts (one entry per trained class).
    export const classRegistry: MlClass[] = [];

    let currentId = 0;
    const confidences: number[] = [];
    const handlers: (() => void)[] = [];
    let anyHandler: ((cls: MlClass) => void) | undefined = undefined;
    // -1 until the first line arrives. With 0 the board would call itself
    // connected for its first three seconds, before it has heard anything.
    let lastHeartbeatMs = -1;

    //% block="when %cls is detected" group="Klassen"
    //% blockId=teachable_on_class
    //% weight=90
    export function onClass(cls: MlClass, handler: () => void): void {
        if (!cls) return;
        handlers[cls.id] = handler;
    }

    //% block="on any class detected" group="Klassen"
    //% blockId=teachable_on_any
    //% draggableParameters=reporter
    //% weight=85
    export function onAnyClass(handler: (detected: MlClass) => void): void {
        anyHandler = handler;
    }

    //% block="detected class" group="Klassen"
    //% blockId=teachable_current_class
    //% weight=80
    export function currentClass(): MlClass {
        return classRegistry[currentId] || classRegistry[0];
    }

    //% block="detected class is %cls" group="Klassen"
    //% blockId=teachable_is_class
    //% weight=78
    export function isClass(cls: MlClass): boolean {
        if (!cls) return false;
        return currentId === cls.id;
    }

    // 0–100 on the class's own calibrated scale, not the model's raw output: the
    // app maps every class onto that scale before sending it, and a class counts
    // as detected from 60 up.
    //% block="confidence of %cls" group="Klassen"
    //% blockId=teachable_confidence
    //% weight=75
    export function confidence(cls: MlClass): number {
        if (!cls) return 0;
        return confidences[cls.id] | 0;
    }

    //% block="connected to Teachable app" group="Klassen"
    //% blockId=teachable_connected
    //% weight=70
    export function isConnected(): boolean {
        if (lastHeartbeatMs < 0) return false;
        return control.millis() - lastHeartbeatMs < 3000;
    }
`;

  const poseBlocks = `
    // --- Pose mode ---

    export enum BodyPart {
        //% block="nose"
        Nose = 0,
        //% block="left eye"
        LeftEye = 1,
        //% block="right eye"
        RightEye = 2,
        //% block="left ear"
        LeftEar = 3,
        //% block="right ear"
        RightEar = 4,
        //% block="left shoulder"
        LeftShoulder = 5,
        //% block="right shoulder"
        RightShoulder = 6,
        //% block="left elbow"
        LeftElbow = 7,
        //% block="right elbow"
        RightElbow = 8,
        //% block="left wrist"
        LeftWrist = 9,
        //% block="right wrist"
        RightWrist = 10,
        //% block="left hip"
        LeftHip = 11,
        //% block="right hip"
        RightHip = 12,
        //% block="left knee"
        LeftKnee = 13,
        //% block="right knee"
        RightKnee = 14,
        //% block="left ankle"
        LeftAnkle = 15,
        //% block="right ankle"
        RightAnkle = 16
    }

    const KP_COUNT = 17;
    const kpX: number[] = [];
    const kpY: number[] = [];
    const kpVis: number[] = [];
    let poseHandler: (() => void) | undefined = undefined;

    //% block="x of %part" group="Pose"
    //% blockId=teachable_body_x
    //% weight=60
    export function bodyPartX(part: BodyPart): number {
        return kpX[part] | 0;
    }

    //% block="y of %part" group="Pose"
    //% blockId=teachable_body_y
    //% weight=59
    export function bodyPartY(part: BodyPart): number {
        return kpY[part] | 0;
    }

    //% block="%part is visible" group="Pose"
    //% blockId=teachable_body_visible
    //% weight=58
    export function isVisible(part: BodyPart): boolean {
        return (kpVis[part] | 0) > 0;
    }

    //% block="distance between %a and %b" group="Pose"
    //% blockId=teachable_distance
    //% weight=57
    export function distanceBetween(a: BodyPart, b: BodyPart): number {
        const dx = (kpX[a] | 0) - (kpX[b] | 0);
        const dy = (kpY[a] | 0) - (kpY[b] | 0);
        return Math.sqrt(dx * dx + dy * dy) | 0;
    }

    //% block="on pose frame" group="Pose"
    //% blockId=teachable_on_pose
    //% weight=56
    export function onPoseFrame(handler: () => void): void {
        poseHandler = handler;
    }

    function parsePoseFrame(rest: string) {
        const parts = rest.split(" ");
        const count = Math.min(Math.idiv(parts.length, 3), KP_COUNT);
        for (let i = 0; i < count; i++) {
            kpX[i] = parseInt(parts[i * 3]);
            kpY[i] = parseInt(parts[i * 3 + 1]);
            kpVis[i] = parseInt(parts[i * 3 + 2]);
        }
        if (poseHandler) poseHandler();
    }
`;

  const parser = `
    // id 0 means nothing is detected: no handler runs, but the detection is
    // cleared, so "detected class is X" goes false and the class fires again
    // when it comes back.
    function setDetected(id: number) {
        if (id === currentId) return;
        currentId = id;
        if (id === 0) return;
        const h = handlers[id];
        if (h) h();
        const cls = classRegistry[id];
        if (anyHandler && cls) anyHandler(cls);
    }

    function handleAllConfidences(rest: string) {
        // Space-separated calibrated confidences (0..100) for class ids 1..N.
        // Which class counts as detected arrives separately on the W line.
        const parts = rest.split(" ");
        for (let i = 0; i < parts.length; i++) {
            confidences[i + 1] = parseInt(parts[i]);
        }
    }

    function handleLine(line: string) {
        if (!line || line.length < 1) return;
        const kind = line.charAt(0);
        if (kind === "D") {
            // <id> <c1> ... <cN>. Confidences first, then the winner, so a
            // handler running on the class event reads its own frame's scores.
            const rest = line.length > 2 ? line.substr(2) : "";
            const sp = rest.indexOf(" ");
            if (sp < 0) {
                setDetected(parseInt(rest) | 0);
            } else {
                handleAllConfidences(rest.substr(sp + 1));
                setDetected(parseInt(rest.substr(0, sp)) | 0);
            }
            lastHeartbeatMs = control.millis();
        } else if (kind === "C") {
            // Split form, from an app that predates the D line.
            const rest = line.length > 2 ? line.substr(2) : "";
            handleAllConfidences(rest);
            lastHeartbeatMs = control.millis();
        } else if (kind === "W") {
            const rest = line.length > 2 ? line.substr(2) : "0";
            setDetected(parseInt(rest) | 0);
            lastHeartbeatMs = control.millis();
        } else if (kind === "H") {
            lastHeartbeatMs = control.millis();
        }${
          mode === 'pose'
            ? ` else if (kind === "P") {
            const rest = line.length > 2 ? line.substr(2) : "";
            parsePoseFrame(rest);
            lastHeartbeatMs = control.millis();
        }`
            : ''
        }
    }

    // The default RX buffer holds 64 bytes, less than one pose frame (~110), so
    // a P line arrived truncated — and a C line for several classes with the W
    // line right behind it can overrun it as well. 254 is the largest the shim
    // takes and leaves room for a second line queued behind the first.
    serial.setRxBufferSize(254);

    // Wire up USB serial. serial.onDataReceived fires per delimiter.
    serial.onDataReceived("\\n", function () {
        const line = serial.readUntil("\\n");
        handleLine(line);
    });

    // Wire up Bluetooth UART so the Teachable app can also stream classifications
    // wirelessly. The board advertises the UART service; the browser pairs via
    // Web Bluetooth. Wrapped in try/catch so missing bluetooth package or no
    // paired central doesn't break USB-only use.
    try {
        bluetooth.startUartService();
        bluetooth.onUartDataReceived("\\n", function () {
            const line = bluetooth.uartReadUntil("\\n");
            handleLine(line);
        });
    } catch (e) { /* bluetooth unavailable */ }
}
`;

  return common + (mode === 'pose' ? poseBlocks : '') + parser;
}
