import type { MakeCodeProject as MkcProject } from '@microbit/makecode-embed';
import { createCalliopeHeader } from './header';
import { classNamesFromLabels, type ClassName } from './names';
import { teachableExtensionSource } from './extension';

export interface GenerateOptions {
  /** Project name shown in MakeCode's title bar. */
  name: string;
  /** 'image' hides pose blocks from the toolbox. */
  mode: 'image' | 'pose';
  /** User class labels in display order. */
  classes: string[];
  /** Optional: per-class threshold (0–100) keyed by class label. */
  thresholds?: Record<string, number>;
  /** Optional: raw dataset for round-trip. */
  dataset?: unknown;
}

const FILES = {
  pxtJson: 'pxt.json',
  mainTs: 'main.ts',
  mainBlocks: 'main.blocks',
  teachableTs: 'teachable.ts',
  autogenerated: 'autogenerated.ts',
  datasetJson: 'dataset.json',
  readme: 'README.md',
} as const;

function generatePxtJson(name: string): string {
  return JSON.stringify(
    {
      name,
      description: '',
      dependencies: {
        core: '*',
        v3: '*',
        serial: '*',
      },
      files: [
        FILES.mainBlocks,
        FILES.mainTs,
        FILES.teachableTs,
        FILES.autogenerated,
        FILES.datasetJson,
        FILES.readme,
      ],
      preferredEditor: 'blocksprj',
    },
    null,
    2,
  );
}

function generateAutogenerated(
  classes: ClassName[],
  mode: 'image' | 'pose',
  thresholds?: Record<string, number>,
): string {
  const lines: string[] = [
    '// Auto-generated. Do not edit — regenerated every time the Teachable app trains.',
    'namespace teachable {',
  ];
  for (const c of classes) {
    const label = c.label.replace(/"/g, '\\"');
    lines.push(`    //% fixedInstance block="${label}"`);
    lines.push(`    export const ${c.variable} = new MlClass(${c.id}, "${label}");`);
  }
  if (classes.length > 0) {
    lines.push('');
    lines.push('    // Populate the registry so currentClass() resolves by id.');
    for (const c of classes) {
      lines.push(`    classRegistry[${c.id}] = ${c.variable};`);
    }
    // Seed per-class default thresholds from the training view. resetThreshold()
    // restores to these; getThreshold() falls back to these until overridden.
    lines.push('');
    lines.push('    // Defaults reflect the thresholds set in the Teachable app.');
    for (const c of classes) {
      const raw = thresholds?.[c.label];
      const pct = typeof raw === 'number'
        ? Math.max(0, Math.min(100, Math.round(raw)))
        : 60;
      lines.push(`    defaultThresholds[${c.id}] = ${pct};`);
    }
  }
  lines.push(`    // Mode flag exposed for code that wants to branch at runtime.`);
  lines.push(`    export const MODE = "${mode}";`);
  lines.push('}');
  return lines.join('\n');
}

function generateMainTs(classes: ClassName[], mode: 'image' | 'pose'): string {
  // Thresholds are seeded inside the auto-generated extension file
  // (defaultThresholds[...]) so main.ts stays focused on the student's logic.
  if (classes.length === 0) {
    return '// Your code here — train classes in the Teachable app to see them as blocks.\n';
  }
  const lines: string[] = [];
  for (const c of classes) {
    lines.push(`teachable.onClass(teachable.${c.variable}, function () {`);
    lines.push(`    basic.showString("${c.label.replace(/"/g, '\\"')}");`);
    lines.push(`});`);
  }
  if (mode === 'pose') {
    lines.push('');
    lines.push('// Pose-Beispiel: reagiere auf jede Pose-Frame (17 Körperpunkte).');
    lines.push('teachable.onPoseFrame(function () {');
    lines.push('    // z. B. Handgelenk-Position lesen:');
    lines.push('    // const x = teachable.bodyPartX(teachable.BodyPart.RightWrist)');
    lines.push('});');
  }
  return lines.join('\n') + '\n';
}

function generateMainBlocks(classes: ClassName[]): string {
  const header =
    '<xml xmlns="https://developers.google.com/blockly/xml"><variables></variables>';
  const footer = '</xml>';
  if (classes.length === 0) {
    return header + footer;
  }
  const blocks = classes
    .map((c, i) => {
      const y = i * 180;
      const label = c.label.replace(/</g, '&lt;').replace(/&/g, '&amp;');
      return (
        `<block type="teachable_on_class" x="0" y="${y}">` +
        `<field name="cls">teachable.${c.variable}</field>` +
        `<statement name="HANDLER">` +
        `<block type="basic_show_string">` +
        `<value name="text"><shadow type="text"><field name="TEXT">${label}</field></shadow></value>` +
        `</block>` +
        `</statement>` +
        `</block>`
      );
    })
    .join('');
  return header + blocks + footer;
}

function generateReadme(opts: GenerateOptions, classes: ClassName[]): string {
  const classLines = classes.length
    ? classes.map((c) => `- **${c.label}**`).join('\n')
    : '_(Noch keine Klassen trainiert. Trainiere Klassen in der Teachable Calliope App, damit sie hier als Blöcke erscheinen.)_';
  const modeLabel = opts.mode === 'pose' ? 'Körperhaltung (Pose)' : 'Bild (Objekt)';
  return (
    `# ${opts.name}\n\n` +
    `Erstellt mit der **Teachable Calliope App**.\n\n` +
    `## Modus\n\n` +
    `${modeLabel}\n\n` +
    `## Trainierte Klassen\n\n` +
    `${classLines}\n\n` +
    `## Wie es funktioniert\n\n` +
    `Die Teachable-App streamt Erkennungen per Serial an den Calliope mini. ` +
    `Das Programm kann auf jede Klasse mit dem Block *"wenn erkannt"* reagieren.\n`
  );
}

export function generateProject(opts: GenerateOptions): MkcProject {
  const classes = classNamesFromLabels(opts.classes);
  const text: Record<string, string> = {
    [FILES.pxtJson]: generatePxtJson(opts.name),
    [FILES.teachableTs]: teachableExtensionSource(opts.mode),
    [FILES.autogenerated]: generateAutogenerated(classes, opts.mode, opts.thresholds),
    [FILES.mainTs]: generateMainTs(classes, opts.mode),
    [FILES.mainBlocks]: generateMainBlocks(classes),
    [FILES.readme]: generateReadme(opts, classes),
    [FILES.datasetJson]: JSON.stringify(opts.dataset ?? {}, null, 2),
  };
  return {
    header: createCalliopeHeader(opts.name) as unknown as MkcProject['header'],
    text,
  };
}

/** Minimal Calliope-targeted project used while the user hasn't trained yet. */
export function createCalliopeSeedProject(): MkcProject {
  return generateProject({
    name: 'Untitled',
    mode: 'image',
    classes: [],
  });
}
