import type { MakeCodeProject as MkcProject } from '@microbit/makecode-embed';
import { createCalliopeHeader } from './header';
import { classNamesFromLabels, type ClassName } from './names';
import { teachableExtensionSource } from './extension';

export interface GenerateOptions {
  /** Project name shown in MakeCode's title bar. */
  name: string;
  /** 'image' hides pose blocks from the toolbox. */
  mode: 'image' | 'pose';
  /** User class labels in display order. */
  classes: string[];
  /** Optional: raw dataset for round-trip. */
  dataset?: unknown;
}

const FILES = {
  pxtJson: 'pxt.json',
  mainTs: 'main.ts',
  mainBlocks: 'main.blocks',
  teachableTs: 'teachable.ts',
  autogenerated: 'autogenerated.ts',
  datasetJson: 'dataset.json',
} as const;

function generatePxtJson(name: string): string {
  return JSON.stringify(
    {
      name,
      description: '',
      dependencies: {
        core: '*',
        v3: '*',
        bluetooth: '*',
      },
      files: [
        FILES.mainBlocks,
        FILES.mainTs,
        FILES.teachableTs,
        FILES.autogenerated,
        FILES.datasetJson,
      ],
      preferredEditor: 'blocksprj',
    },
    null,
    2,
  );
}

function generateAutogenerated(
  classes: ClassName[],
  mode: 'image' | 'pose',
): string {
  const lines: string[] = [
    '// Auto-generated. Do not edit — regenerated every time the Teachable app trains.',
    'namespace teachable {',
  ];
  for (const c of classes) {
    // Label is already JSON-safe (see sanitizeLabel in names.ts): no control
    // chars, no backslashes, no double-quotes — so it can be inlined directly.
    lines.push(`    //% fixedInstance block="${c.label}"`);
    lines.push(`    export const ${c.variable} = new MlClass(${c.id}, "${c.label}");`);
  }
  if (classes.length > 0) {
    lines.push('');
    lines.push('    // Populate the registry so currentClass() resolves by id.');
    for (const c of classes) {
      lines.push(`    classRegistry[${c.id}] = ${c.variable};`);
    }
  }
  lines.push(`    // Mode flag exposed for code that wants to branch at runtime.`);
  lines.push(`    export const MODE = "${mode}";`);
  lines.push('}');
  return lines.join('\n');
}

function generateMainTs(classes: ClassName[], mode: 'image' | 'pose'): string {
  if (classes.length === 0) {
    return '// Your code here — train classes in the Teachable app to see them as blocks.\n';
  }
  const lines: string[] = [];
  for (const c of classes) {
    lines.push(`teachable.onClass(teachable.${c.variable}, function () {`);
    lines.push(`    basic.showString("${c.label}");`);
    lines.push(`});`);
  }
  if (mode === 'pose') {
    lines.push('');
    lines.push('// Pose-Beispiel: reagiere auf jede Pose-Frame (17 Körperpunkte).');
    lines.push('teachable.onPoseFrame(function () {');
    lines.push('    // z. B. Handgelenk-Position lesen:');
    lines.push('    // const x = teachable.bodyPartX(teachable.BodyPart.RightWrist)');
    lines.push('});');
  }
  return lines.join('\n') + '\n';
}

function generateMainBlocks(classes: ClassName[]): string {
  const header =
    '<xml xmlns="https://developers.google.com/blockly/xml"><variables></variables>';
  const footer = '</xml>';
  if (classes.length === 0) {
    return header + footer;
  }
  const blocks = classes
    .map((c, i) => {
      const y = i * 180;
      const label = c.label.replace(/</g, '&lt;').replace(/&/g, '&amp;');
      return (
        `<block type="teachable_on_class" x="0" y="${y}">` +
        `<field name="cls">teachable.${c.variable}</field>` +
        `<statement name="HANDLER">` +
        `<block type="basic_show_string">` +
        `<value name="text"><shadow type="text"><field name="TEXT">${label}</field></shadow></value>` +
        `</block>` +
        `</statement>` +
        `</block>`
      );
    })
    .join('');
  return header + blocks + footer;
}

export function generateProject(opts: GenerateOptions): MkcProject {
  const classes = classNamesFromLabels(opts.classes);
  const text: Record<string, string> = {
    [FILES.pxtJson]: generatePxtJson(opts.name),
    [FILES.teachableTs]: teachableExtensionSource(opts.mode),
    [FILES.autogenerated]: generateAutogenerated(classes, opts.mode),
    [FILES.mainTs]: generateMainTs(classes, opts.mode),
    [FILES.mainBlocks]: generateMainBlocks(classes),
    [FILES.datasetJson]: JSON.stringify(opts.dataset ?? {}, null, 2),
  };
  return {
    header: createCalliopeHeader(opts.name) as unknown as MkcProject['header'],
    text,
  };
}

/** Minimal Calliope-targeted project used while the user hasn't trained yet. */
export function createCalliopeSeedProject(): MkcProject {
  return generateProject({
    name: 'Untitled',
    mode: 'image',
    classes: [],
  });
}
