/**
 * How a generated MakeCode project names its classes.
 *
 * Two separate things used to be one here: what a class is called, and how the
 * program refers to it. The `fixedInstance` variable was derived from the label,
 * so `main.blocks` addressed a class as `teachable.Hand` — which bound the
 * program to one exact class list. Generating the class list for a model with
 * other labels left every saved block pointing at an identifier that no longer
 * existed, so a program could only ever run on models trained on the very same
 * names.
 *
 * The variable is now the class index and nothing else. The label lives only in
 * the `block="..."` attribute, which is display text: rewriting it retitles the
 * blocks a student already placed instead of breaking them. That is what lets a
 * program run on any model — the wire protocol was index-based all along (see
 * extension.ts), and now the blocks are too.
 */

export interface ClassName {
  /** User-facing label. Only ever the `block="..."` dropdown text. */
  label: string;
  /** `Class<id>`. The same for every model, so saved blocks keep resolving. */
  variable: string;
  /** 1-based id: the wire id and the registry slot. */
  id: number;
}

/** The `fixedInstance` const name for a 1-based class id. */
export function classVariable(id: number): string {
  return `Class${id}`;
}

/**
 * Sanitize a user label for use inside a MakeCode JSDoc attribute like
 * `block="..."`. MakeCode's comment parser reads each attribute value as a
 * JSON string, so any raw backslash or control character the user typed will
 * crash the TS worker with `Bad escaped character in JSON at position ...`.
 * Drop control chars, flatten backslashes/quotes, collapse whitespace.
 */
function sanitizeLabel(raw: string): string {
  let out = '';
  for (let i = 0; i < raw.length; i++) {
    const code = raw.charCodeAt(i);
    if (code < 0x20 || code === 0x7f) {
      out += ' ';
      continue;
    }
    const ch = raw[i];
    out += ch === '\\' || ch === '"' ? "'" : ch;
  }
  return out.replace(/\s+/g, ' ').trim();
}

/** Turn user labels into `{ label, variable, id }` in wire order. */
export function classNamesFromLabels(labels: string[]): ClassName[] {
  return labels.map((raw, i) => ({
    label: sanitizeLabel(raw ?? '') || `Klasse ${i + 1}`,
    variable: classVariable(i + 1),
    id: i + 1,
  }));
}

/**
 * A class slot the open program uses but the loaded model doesn't have. The
 * block stays in the toolbox and keeps resolving — it just never fires, because
 * no model ever sends that id. Named so that is visible in the dropdown rather
 * than a class that looks trained and silently does nothing.
 */
export function missingClassName(id: number): ClassName {
  return { label: `Klasse ${id} (nicht im Modell)`, variable: classVariable(id), id };
}

// ---- Migration off the old, label-derived names ------------------------------

function stripAccents(s: string): string {
  return s.normalize('NFKD').replace(/\p{M}/gu, '');
}

/** The identifier the old generator built from a label. */
function legacyVariable(label: string): string {
  const asciiish = stripAccents(label).replace(/[^a-zA-Z0-9 _]/g, ' ');
  const parts = asciiish
    .split(/[\s_]+/)
    .filter(Boolean)
    .map((p) => {
      const low = p.toLowerCase();
      return low.charAt(0).toUpperCase() + low.slice(1);
    });
  const safe = parts.join('').replace(/[^A-Za-z0-9_]/g, '');
  return /^[0-9]/.test(safe) ? `_${safe}` : safe || 'Class';
}

/**
 * Identifiers the extension itself exports. A label like "Body Part" produced
 * one of these, and renaming it in a program that also uses the real member
 * would rewrite both — so those are left alone. Such a program never compiled
 * anyway: its `autogenerated.ts` declared the name a second time.
 */
const EXTENSION_MEMBERS = new Set([
  'MlClass',
  'BodyPart',
  'MODE',
  'classRegistry',
  'onClass',
  'onAnyClass',
  'currentClass',
  'isClass',
  'confidence',
  'isConnected',
  'bodyPartX',
  'bodyPartY',
  'isVisible',
  'distanceBetween',
  'onPoseFrame',
]);

/**
 * Old identifier → `Class<n>` for a program's stored class list, in wire order.
 * Only what {@link legacyVariable} would have produced, so nothing a student
 * typed themselves is caught: the map is looked up by exact name.
 */
export function legacyVariableMap(labels: string[]): Map<string, string> {
  const map = new Map<string, string>();
  const seen = new Set<string>();
  labels.forEach((raw, i) => {
    const label = sanitizeLabel(raw ?? '') || `Class${i + 1}`;
    let variable = legacyVariable(label);
    // The old generator suffixed collisions the same way.
    let suffix = 2;
    const base = variable;
    while (seen.has(variable)) {
      variable = `${base}${suffix++}`;
    }
    seen.add(variable);
    const next = classVariable(i + 1);
    if (variable !== next && !EXTENSION_MEMBERS.has(variable)) map.set(variable, next);
  });
  return map;
}
