/**
 * Facts read off a stored program's file map.
 *
 * A program no longer records which model it was generated for. What it needs
 * from a model — how many class slots its blocks address, and whether the pose
 * blocks have to stay in the toolbox — is visible in the files themselves, and
 * reading it there means it stays true when a student adds or deletes blocks.
 * Nothing here parses the files properly; these are the two questions the
 * regenerator asks before it rewrites the generated half of a project.
 */

import { legacyVariableMap } from './names';

/** The files a student edits. Everything else in a project is generated. */
const AUTHORED = ['main.ts', 'main.blocks'] as const;

/** Every `teachable.<name>` reference in the code and the blocks XML. */
const REFERENCE = /teachable\.([A-Za-z_$][A-Za-z0-9_$]*)/g;

/** The mode a stored program was generated for, read off its `autogenerated.ts`. */
export function storedMode(files: Record<string, string>): 'image' | 'pose' | null {
  const m = /MODE\s*=\s*"(image|pose)"/.exec(files['autogenerated.ts'] ?? '');
  return m ? (m[1] as 'image' | 'pose') : null;
}

/**
 * The highest class slot the program's own files address, or 0 for a program
 * with no class blocks. The generated class list has to reach at least this far
 * or a block a student placed would point at a class that isn't declared.
 */
export function highestClassIndex(files: Record<string, string>): number {
  let highest = 0;
  for (const name of AUTHORED) {
    const source = files[name] ?? '';
    for (const [, ref] of source.matchAll(REFERENCE)) {
      const m = /^Class(\d+)$/.exec(ref);
      if (m) highest = Math.max(highest, parseInt(m[1], 10));
    }
  }
  return highest;
}

/**
 * Whether the program uses pose blocks. Generating `teachable.ts` for an image
 * model drops them, which would delete blocks a student is using — so the mode
 * of the regenerated extension is the union of what the model is and what the
 * program already needs.
 */
export function usesPoseBlocks(files: Record<string, string>): boolean {
  const pose =
    /teachable\.(bodyPartX|bodyPartY|isVisible|distanceBetween|onPoseFrame|BodyPart)|teachable_(body_|on_pose|distance)/;
  return AUTHORED.some((name) => pose.test(files[name] ?? ''));
}

/**
 * Rewrite label-derived class references to the index-based names.
 *
 * Programs saved before class identity was split from the class label address
 * their classes as `teachable.<LabelInPascalCase>`. Those identifiers only exist
 * while the generated class list carries that program's original labels, which
 * is exactly what no longer holds. `labels` is the program's stored class list —
 * the order the ids came from — so the old name of every slot can be
 * reconstructed and pointed at `Class<n>`.
 *
 * One pass over the references rather than a replace per name: `Hand` is a
 * prefix of `Hand2`, and replacing the shorter one first would leave `Class12`
 * where `Class2` belonged.
 */
export function withIndexedClassRefs(
  files: Record<string, string>,
  labels: string[]
): Record<string, string> {
  const map = legacyVariableMap(labels);
  if (!map.size) return files;
  const next = { ...files };
  for (const name of AUTHORED) {
    const source = next[name];
    if (!source) continue;
    next[name] = source.replace(REFERENCE, (whole, ref: string) => {
      const renamed = map.get(ref);
      return renamed ? `teachable.${renamed}` : whole;
    });
  }
  return next;
}
