import { describe, it, expect } from 'vitest';
import { autogeneratedSource } from './generate';
import { highestClassIndex, usesPoseBlocks, withIndexedClassRefs } from './programFiles';

const blocks = (...fields: string[]) =>
  `<xml>${fields.map((f) => `<block type="teachable_on_class"><field name="cls">${f}</field></block>`).join('')}</xml>`;

describe('highestClassIndex', () => {
  it('is 0 for a program without class blocks', () => {
    expect(highestClassIndex({ 'main.blocks': '<xml></xml>', 'main.ts': '' })).toBe(0);
  });

  it('finds the highest slot across code and blocks', () => {
    expect(
      highestClassIndex({
        'main.blocks': blocks('teachable.Class1', 'teachable.Class3'),
        'main.ts': 'teachable.onClass(teachable.Class2, function () {})'
      })
    ).toBe(3);
  });

  it(`ignores the extension's own members`, () => {
    expect(
      highestClassIndex({ 'main.ts': 'teachable.bodyPartX(teachable.BodyPart.Nose)' })
    ).toBe(0);
  });

  it('ignores generated files, which are rewritten anyway', () => {
    expect(
      highestClassIndex({ 'autogenerated.ts': 'classRegistry[9] = teachable.Class9;' })
    ).toBe(0);
  });
});

describe('usesPoseBlocks', () => {
  it('sees a pose block in the blocks XML', () => {
    expect(usesPoseBlocks({ 'main.blocks': '<block type="teachable_body_x"></block>' })).toBe(true);
  });

  it('is false for a program that only classifies', () => {
    expect(usesPoseBlocks({ 'main.blocks': blocks('teachable.Class1') })).toBe(false);
  });
});

describe('withIndexedClassRefs', () => {
  it('rewrites label-derived names to their slot', () => {
    const out = withIndexedClassRefs(
      { 'main.blocks': blocks('teachable.Hand', 'teachable.Faust') },
      ['Hand', 'Faust']
    );
    expect(out['main.blocks']).toBe(blocks('teachable.Class1', 'teachable.Class2'));
  });

  it('does not let one name eat the prefix of another', () => {
    // Both labels produced `Hand`, so the old generator suffixed the second to
    // `Hand2`. Replacing `Hand` first would have left `Class12` behind.
    const out = withIndexedClassRefs(
      { 'main.ts': 'teachable.Hand2; teachable.Hand;' },
      ['Hand', 'hand']
    );
    expect(out['main.ts']).toBe('teachable.Class2; teachable.Class1;');
  });

  it(`leaves the extension API and the student's own names alone`, () => {
    const src = 'teachable.onClass(teachable.Hand, function () { myHand(); })';
    const out = withIndexedClassRefs({ 'main.ts': src }, ['Hand']);
    expect(out['main.ts']).toBe(
      'teachable.onClass(teachable.Class1, function () { myHand(); })'
    );
  });

  it('never touches the generated files', () => {
    const files = { 'autogenerated.ts': 'const Hand = new MlClass(1, "Hand");' };
    expect(withIndexedClassRefs(files, ['Hand'])).toEqual(files);
  });
});

describe('autogeneratedSource', () => {
  it('names slots by index and labels them from the model', () => {
    const src = autogeneratedSource({ classes: ['Hand', 'Faust'], mode: 'image' });
    expect(src).toContain('//% fixedInstance block="Hand"');
    expect(src).toContain('export const Class1 = new MlClass(1, "Hand");');
    expect(src).toContain('export const Class2 = new MlClass(2, "Faust");');
  });

  it('pads up to the slots a program still uses', () => {
    const src = autogeneratedSource({
      classes: ['Hand'],
      mode: 'image',
      minClassCount: 3
    });
    // The blocks for slots 2 and 3 keep resolving; they just never fire.
    expect(src).toContain('export const Class2 = new MlClass(2, "Klasse 2 (nicht im Modell)");');
    expect(src).toContain('classRegistry[3] = Class3;');
  });

  it('declares nothing extra when the model covers every slot', () => {
    const src = autogeneratedSource({
      classes: ['Hand', 'Faust'],
      mode: 'image',
      minClassCount: 2
    });
    expect(src).not.toContain('Class3');
  });
});
